//  Declaration.swift
//  The device's `Peer` declaration (`CORE` §5.2), built out of `libppcp`'s own
//  structs from what the real capture stack enumerated.
//
//  ⚠ **REQ-PORT-11 in one sentence: the Swift capability types are now *views
//  over* the library's structs, not a parallel vocabulary.** `DeviceCapability`,
//  `VideoMode`, `Lens` and `MeasuredCapability` describe the device for a
//  *screen*; `ppcp_peer_desc`, `ppcp_source`, `ppcp_capture_profile` and
//  `ppcp_measured_capability` describe it for a *peer*. This file is the one
//  place the first becomes the second, and there is deliberately no second place:
//  two translations drift, and the drift is invisible because each half looks
//  right on its own.
//
//  ⛔ **Every structural invariant below is the library's, not this file's.**
//  I22 (`frame_start_to_exposure_offset_ns` present iff `nominal_frame_start`) is
//  held by there being two constructors in `timing.h` and only one of them taking
//  an offset. I31 (provenance on every unmeasured constant) is held by provenance
//  being a *parameter* of both constructors. I28 (`measured` means measured) is
//  held by `ppcp_measured_capability_make` taking a method and a duration and by
//  there being no constructor from a profile or a table. This file cannot
//  produce the malformed shapes even by trying, which is the whole reason the
//  declaration is assembled through the C API rather than encoded in Swift.
//
//  Spec: `CORE` §5.2, §5.3, §5.6, §5.6.1, §5.7, §5.8; `CONF` CT-I4, CT-I19,
//  CT-I22, CT-I28, CT-I31, CT-S7 1–3. Decisions: A12, A13.

import Foundation
import CPPCP

// MARK: - Timebases

/// `CORE` §5.3 — a clock this peer declares, in neutral terms.
///
/// ⚠ Every field is the platform's to *report*, not this layer's to assume:
/// `resolution_ns` comes from `mach_timebase_info` on iOS and from something else
/// on the next platform, and `kind` is a property of the specific clock the
/// samples are in. See `PpcpTimebases` in `Sources/Platform` for the readings and
/// for the finding about which clock AVFoundation actually stamps with.
public struct PpcpTimebaseDeclaration: Sendable, Hashable {

    public enum Kind: Sendable, Hashable {
        /// Halts across device sleep.
        case monotonic
        /// Does not.
        case continuous
        /// Subject to jumps, and **label-only** (5.3b, I15).
        case wall
    }

    public let id: String
    public let kind: Kind
    public let epochStable: Bool
    public let resolutionNs: Int64
    /// `CORE` 5.3 — "opaque and informational, e.g. `CMClockGetHostTimeClock`.
    /// MUST NOT be interpreted."
    public let origin: String?

    public init(id: String, kind: Kind, epochStable: Bool,
                resolutionNs: Int64, origin: String? = nil) {
        self.id = id
        self.kind = kind
        self.epochStable = epochStable
        self.resolutionNs = resolutionNs
        self.origin = origin
    }

    var cKind: ppcp_timebase_kind {
        switch kind {
        case .monotonic: PPCP_TB_MONOTONIC
        case .continuous: PPCP_TB_CONTINUOUS
        case .wall: PPCP_TB_WALL
        }
    }
}

// MARK: - Viewpoint

/// `CORE` 5.6e — "declares **how it was arrived at** … and carries `confidence`
/// **only** in the second case."
///
/// ⛔ The two cases are separate values with separate payloads, so a `declared`
/// viewpoint has nowhere to put a confidence. 5.6e: "A person who states 'down
/// the line' is not expressing a probability, and requiring a number there would
/// be asking a peer to invent one, which is the pattern I28 and I31 exist to
/// prevent."
public enum PpcpViewpoint: Sendable, Hashable {
    /// A user or installer stated it.
    case declared(label: String)
    /// The peer worked it out, and only then a confidence.
    case classified(label: String, confidence: Double)
}

// MARK: - What a declaration is built from

/// Everything the declaration needs, in neutral terms. ⚠ Assembled by the
/// platform layer from the real capture stack (`AVFoundationCaptureDevice`) and
/// the model's `DeviceProfiles.json` entry — never from a spec sheet (REQ-FPS-1)
/// and never from `product` (5.2c, I19).
public struct PpcpDeclarationInput: Sendable {

    /// `CORE` 5.2.1a — generated by the peer and persisted in its own store.
    /// ⛔ 5.2.1b: never a platform device identifier or an advertising identifier.
    public var peerId: String
    /// `CORE` §10.1 — the wire version this peer speaks. Asked of the library.
    public var protocolVersion: String
    /// `CORE` 5.2 — MUST include `core`. Plan §2: this application's set.
    public var profiles: [String]

    public var timebases: [PpcpTimebaseDeclaration]
    /// Which of them every Source is on. `CORE` 5.3 / I4: "Two Sources on the
    /// same clock reference the **same** `Timebase.id`."
    public var captureTimebaseId: String

    public var capability: DeviceCapability
    public var timing: PpcpDeviceTimingProfile

    /// `CORE` 5.7 `format.codec`. See the ⚠ where it is written.
    public var clipCodec: String

    public var declaresMicrophone: Bool
    public var declaresIMU: Bool
    public var viewpoint: PpcpViewpoint?

    /// `CORE` 5.2 `product` — informational. ⛔ 5.2c: a peer MUST NOT infer any
    /// capability, convention or geometry from it (I19), which is why it is last
    /// and why nothing in this file reads it back.
    public var product: (vendor: String, model: String, version: String)?

    public init(peerId: String,
                protocolVersion: String = PpcpLibrary.wireVersion,
                profiles: [String],
                timebases: [PpcpTimebaseDeclaration],
                captureTimebaseId: String,
                capability: DeviceCapability,
                timing: PpcpDeviceTimingProfile,
                clipCodec: String,
                declaresMicrophone: Bool = true,
                declaresIMU: Bool = true,
                viewpoint: PpcpViewpoint? = nil,
                product: (vendor: String, model: String, version: String)? = nil) {
        self.peerId = peerId
        self.protocolVersion = protocolVersion
        self.profiles = profiles
        self.timebases = timebases
        self.captureTimebaseId = captureTimebaseId
        self.capability = capability
        self.timing = timing
        self.clipCodec = clipCodec
        self.declaresMicrophone = declaresMicrophone
        self.declaresIMU = declaresIMU
        self.viewpoint = viewpoint
        self.product = product
    }
}

/// The profile set of `CORE` §2.2.3, "full mobile capture device", asked of the
/// library rather than spelled here (plan §2). ⛔ `arbitrate` is absent and must
/// stay absent: I20 makes it host-only, and the negative test of `CONF` §1d is
/// that this application parses `capture_request` and never originates one.
public enum PpcpProfileSet {
    // ⚠ The macros of `model.h` import into Swift as `String` already — they are
    // `#define`d string literals, not `char *` — so they are used directly. A
    // `String(cString:)` around one is both deprecated and a copy of a copy.
    public static let device: [String] = [
        PPCP_PROFILE_CORE,
        PPCP_PROFILE_CAPTURE,
        PPCP_PROFILE_DETECT,
        PPCP_PROFILE_MINT,
        PPCP_PROFILE_LIVE,
        PPCP_PROFILE_OFFLINE,
        PPCP_PROFILE_MARKUP
    ]
}

// MARK: - The declaration

/// A built, validated `ppcp_peer_desc` and the storage its pointers refer to.
///
/// ⚠ **A class with manually allocated storage, and it has to be.** `libppcp`
/// allocates nothing (plan ground rule 7), so `ppcp_peer_desc.sources`,
/// `ppcp_source.profiles` and the rest are borrowed pointers into memory the
/// caller owns for as long as the declaration is used. Swift arrays give no such
/// promise — `withUnsafeBufferPointer` is valid only inside its closure, and a
/// three-level nest of those to reach one encode is unreadable and easy to get
/// subtly wrong. So the buffers are allocated once here and freed in `deinit`,
/// and the object's lifetime *is* the pointers' lifetime.
///
/// ⛔ Immutable after `init`. `@unchecked Sendable` rests on that and on nothing
/// else: there is no setter, no lazy field and no cache.
public final class PpcpDeclaration: @unchecked Sendable {

    // ── Views (REQ-PORT-11) ──────────────────────────────────────────────────
    //
    // ⚠ **Read back OUT of the C structs after they are built, never assembled
    // alongside them.** A view built from the same Swift values that fed the
    // constructors would agree with itself whatever the library did, and would
    // certify a bug rather than catch one — which is the single-implementation
    // trap `CONF` §2c describes, in miniature. These read what will actually be
    // encoded, so a test that asserts on a view is asserting on the wire.

    /// `CORE` 5.7 `Timing.convention`.
    public enum Convention: String, Sendable, Hashable {
        case mid, start, end
        case nominalFrameStart = "nominal_frame_start"
    }

    /// `CORE` 5.7 `geometry`.
    public enum Geometry: Sendable, Hashable {
        case global
        case rollingShutter(readoutNs: Int64, provenance: PpcpProvenance,
                            direction: PpcpRollingDirection, rows: Int)
    }

    public enum Intrinsics: String, Sendable, Hashable {
        case perFrame = "per_frame"
        case fixed, none
    }

    /// One `CaptureProfile`, as the library holds it.
    public struct ProfileView: Sendable, Hashable {
        public let id: String
        public let convention: Convention
        /// ⛔ I22 — present **if and only if** `convention == .nominalFrameStart`.
        /// The library's two constructors make any other combination
        /// unconstructible; this is where a test can see that.
        public let offsetNs: Int64?
        public let offsetProvenance: PpcpProvenance?
        public let geometry: Geometry?
        public let intrinsics: Intrinsics?
        public let rateMillihertz: Int64?
        public let format: (codec: String, width: Int, height: Int, pixelFormat: String)?
        /// I28 — `false` means **not measured**, and there is no other meaning.
        public let measuredMethod: MeasuredCapability.Method?

        public static func == (a: Self, b: Self) -> Bool { a.id == b.id }
        public func hash(into hasher: inout Hasher) { hasher.combine(id) }
    }

    /// One Source, as the rest of the application wants to read it back.
    public struct SourceView: Sendable, Hashable {
        public let id: String
        public let kind: String
        public let timebaseId: String
        public let optics: String?
        public let physical: Bool
        public let profiles: [ProfileView]

        public var profileIds: [String] { profiles.map(\.id) }
    }

    private let timebaseStorage: UnsafeMutableBufferPointer<ppcp_timebase>
    private let profileIdStorage: UnsafeMutableBufferPointer<ppcp_id>
    private let captureProfileStorage: UnsafeMutableBufferPointer<ppcp_capture_profile>
    private let sourceStorage: UnsafeMutableBufferPointer<ppcp_source>
    private let descStorage: UnsafeMutablePointer<ppcp_peer_desc>

    /// ⚠ **`var` with a default, not `let`, and the reason is memory safety
    /// rather than mutability.** A class initialiser that throws runs `deinit`
    /// only once every stored property has a value; with a `let` assigned
    /// half-way through, whether the storage was released once or twice depended
    /// on *where* the throw happened. Giving it a value up front makes `deinit`
    /// the single owner, which is what let the `catch` below stop releasing.
    public private(set) var sources: [SourceView] = []

    public init(_ input: PpcpDeclarationInput) throws {
        // ── Sources, planned before anything is allocated ─────────────────────
        let plans = try Self.plan(input)

        let profileTotal = plans.reduce(0) { $0 + $1.profiles.count }
        timebaseStorage = .allocate(capacity: max(input.timebases.count, 1))
        profileIdStorage = .allocate(capacity: max(input.profiles.count, 1))
        captureProfileStorage = .allocate(capacity: max(profileTotal, 1))
        sourceStorage = .allocate(capacity: max(plans.count, 1))
        descStorage = .allocate(capacity: 1)
        timebaseStorage.initialize(repeating: ppcp_timebase())
        profileIdStorage.initialize(repeating: ppcp_id())
        captureProfileStorage.initialize(repeating: ppcp_capture_profile())
        sourceStorage.initialize(repeating: ppcp_source())
        descStorage.initialize(to: ppcp_peer_desc())

        do {
            // ── Timebases (5.3a: declared before or with the Sources) ─────────
            for (index, timebase) in input.timebases.enumerated() {
                try check(ppcp_timebase_make(timebaseStorage.baseAddress! + index,
                                             timebase.id, timebase.id.utf8.count,
                                             timebase.cKind, timebase.epochStable,
                                             timebase.resolutionNs))
                if let origin = timebase.origin {
                    try check(ppcp_timebase_set_origin(timebaseStorage.baseAddress! + index,
                                                       origin, origin.utf8.count))
                }
                try check(ppcp_timebase_validate(timebaseStorage.baseAddress! + index))
            }

            for (index, profile) in input.profiles.enumerated() {
                try check(ppcp_id_set_z(profileIdStorage.baseAddress! + index, profile))
            }

            // ── Sources and their CaptureProfiles ─────────────────────────────
            //
            // ⚠ The base address is taken into a local before the loop. The view
            // is read back out of the C structs through a closure, and a closure
            // that touched `captureProfileStorage` would be capturing `self`
            // before `sources` is initialised — which Swift refuses, correctly:
            // `self` is not whole yet.
            let profileBase = captureProfileStorage.baseAddress!
            var cursor = 0
            var views: [SourceView] = []
            for (index, plan) in plans.enumerated() {
                let first = cursor
                for profile in plan.profiles {
                    try profile.build(into: captureProfileStorage.baseAddress! + cursor)
                    try check(ppcp_capture_profile_validate(
                        captureProfileStorage.baseAddress! + cursor))
                    cursor += 1
                }
                let source = sourceStorage.baseAddress! + index
                try check(ppcp_source_make(source, plan.id, input.peerId, plan.kind,
                                           plan.timebaseId, plan.physical,
                                           captureProfileStorage.baseAddress! + first,
                                           plan.profiles.count))
                if let optics = plan.optics {
                    try check(ppcp_source_set_optics(source, optics))
                }
                if let label = plan.label {
                    try check(ppcp_source_set_label(source, label))
                }
                switch plan.viewpoint {
                case .declared(let label):
                    try check(ppcp_source_set_viewpoint_declared(source, label))
                case .classified(let label, let confidence):
                    try check(ppcp_source_set_viewpoint_classified(source, label, confidence))
                case nil:
                    break
                }
                try check(ppcp_source_validate(source))
                views.append(SourceView(
                    id: plan.id, kind: plan.kind, timebaseId: plan.timebaseId,
                    optics: plan.optics, physical: plan.physical,
                    profiles: (first..<cursor).map { Self.view(of: profileBase + $0) }))
            }
            sources = views

            // ── The Peer itself ───────────────────────────────────────────────
            try check(ppcp_peer_desc_make(descStorage, input.peerId, PPCP_ROLE_CAPTURE,
                                          input.protocolVersion,
                                          profileIdStorage.baseAddress!, input.profiles.count,
                                          timebaseStorage.baseAddress!, input.timebases.count))
            try check(ppcp_peer_desc_set_sources(descStorage, sourceStorage.baseAddress!,
                                                 plans.count))
            if let product = input.product {
                try check(ppcp_peer_desc_set_product(descStorage, product.vendor,
                                                     product.model, product.version))
            }
            // ⛔ **No `relations`, and that is a claim rather than an omission.**
            // I4: two Sources on one clock reference the *same* `Timebase.id`,
            // and identity is never asserted by a relation. Every Source this
            // device declares is on `captureTimebaseId`, so there is no A→B to
            // declare and a `from == to` relation would be exactly the mistake
            // CT-I4 tests for.
            try check(ppcp_peer_desc_validate(descStorage))
        } catch {
            // ⛔ Nothing is released here: `deinit` owns the storage, and a
            // `catch` that released it too freed the same pointers twice for any
            // throw that happened after the last stored property was set. See the
            // note on `sources`.
            throw error
        }
    }

    deinit {
        Self.release(timebaseStorage, profileIdStorage, captureProfileStorage,
                     sourceStorage, descStorage)
    }

    private static func release(_ timebases: UnsafeMutableBufferPointer<ppcp_timebase>,
                                _ profileIds: UnsafeMutableBufferPointer<ppcp_id>,
                                _ captureProfiles: UnsafeMutableBufferPointer<ppcp_capture_profile>,
                                _ sources: UnsafeMutableBufferPointer<ppcp_source>,
                                _ desc: UnsafeMutablePointer<ppcp_peer_desc>) {
        timebases.deallocate()
        profileIds.deallocate()
        captureProfiles.deallocate()
        sources.deallocate()
        desc.deallocate()
    }

    /// How many `TimebaseRelation`s this peer declares.
    ///
    /// ⛔ Zero, and CT-I4 is why it is exposed: I4 says "identity is a shared
    /// `id`, not a relation", so a device whose camera, microphone and IMU are
    /// all on `tb:hosttime` must declare **no** relation between them — least of
    /// all one with `from == to`. A count is the cheapest thing to assert.
    public var declaredRelationCount: Int { descStorage.pointee.relation_count }

    /// Every profile on every Source, flattened — what CT-I22, CT-I31 and CT-S7
    /// assertions 1 and 2 walk.
    public var allProfiles: [ProfileView] { sources.flatMap(\.profiles) }

    /// Run `body` with the built declaration. ⚠ The pointer is valid only for the
    /// call, because it is valid only while this object is alive and a caller
    /// that squirrelled it away would have no way to know when that stopped.
    public func withPeerDesc<T>(_ body: (UnsafePointer<ppcp_peer_desc>) throws -> T) rethrows -> T {
        try body(UnsafePointer(descStorage))
    }

    /// One declared Source and, where the profile id is given, one of its
    /// `CaptureProfile`s — which is exactly what `ppcp_candidate_make_canonical`
    /// takes (`CORE` 5.12e, I33).
    ///
    /// ⚠ **`profile` is `nil` for a microphone and an IMU, and that is not an
    /// omission.** `CORE` 6.1d fixes `convention: mid` where a profile has no
    /// `format`, so the canonical instant *is* the raw instant and there is
    /// nothing for the conversion to read. Passing a camera profile for an
    /// acoustic candidate would apply a `d/2` the microphone never had.
    ///
    /// - Returns: `nil` where this peer declares no such Source — which is I26's
    ///   refusal one step earlier than the library's, so a caller gets a name it
    ///   can report instead of `PPCP_ERR_INVALID`.
    public func withSource<T>(id sourceId: String, profileId: String? = nil,
                              _ body: (UnsafePointer<ppcp_source>,
                                       UnsafePointer<ppcp_capture_profile>?) throws -> T)
        rethrows -> T? {
        guard let index = sources.firstIndex(where: { $0.id == sourceId }) else { return nil }
        let source = sourceStorage.baseAddress! + index
        guard let profileId else { return try body(UnsafePointer(source), nil) }
        guard let offset = sources[index].profiles.firstIndex(where: { $0.id == profileId })
        else { return try body(UnsafePointer(source), nil) }
        let profile = UnsafeRawPointer(source.pointee.profiles!)
            .assumingMemoryBound(to: ppcp_capture_profile.self) + offset
        return try body(UnsafePointer(source), profile)
    }

    /// The declaration as `ENC` §4 CBOR — what `declare` puts on the wire
    /// (`MSG` §3), and what a bundle's own `declare` frame carries.
    public func encoded() throws -> Data {
        var capacity = 64 * 1024
        while true {
            var buffer = [UInt8](repeating: 0, count: capacity)
            var writer = ppcp_cbor_writer()
            ppcp_cbor_writer_init(&writer, &buffer, capacity)
            let result = withPeerDesc { ppcp_peer_desc_encode(&writer, $0) }
            if result == PPCP_ERR_NOSPACE, capacity < 4 * 1024 * 1024 {
                capacity *= 4
                continue
            }
            try check(result)
            var length = 0
            try check(ppcp_cbor_writer_finish(&writer, &length))
            return Data(buffer[0..<length])
        }
    }

    private static func view(of p: UnsafePointer<ppcp_capture_profile>) -> ProfileView {
        let profile = p.pointee
        let convention: Convention = switch profile.timing.convention {
        case PPCP_CONV_MID: .mid
        case PPCP_CONV_START: .start
        case PPCP_CONV_END: .end
        default: .nominalFrameStart
        }
        let geometry: Geometry? = profile.has_geometry
            ? (profile.geometry.kind == PPCP_GEOM_GLOBAL
                ? .global
                : .rollingShutter(
                    readoutNs: profile.geometry.readout_ns,
                    provenance: provenance(profile.geometry.readout_provenance),
                    direction: profile.geometry.direction == PPCP_ROLL_TOP_TO_BOTTOM
                        ? .topToBottom : .bottomToTop,
                    rows: Int(profile.geometry.rows)))
            : nil
        let intrinsics: Intrinsics? = intrinsicsView(profile)
        return ProfileView(
            id: text(profile.id),
            convention: convention,
            offsetNs: profile.timing.has_offset
                ? profile.timing.frame_start_to_exposure_offset_ns : nil,
            offsetProvenance: profile.timing.has_offset
                ? provenance(profile.timing.offset_provenance) : nil,
            geometry: geometry,
            intrinsics: intrinsics,
            rateMillihertz: profile.rate.present ? profile.rate.nominal_mhz : nil,
            format: profile.format.present
                ? (codec: text(profile.format.codec), width: Int(profile.format.width),
                   height: Int(profile.format.height),
                   pixelFormat: text(profile.format.pixel_format))
                : nil,
            measuredMethod: profile.has_measured
                ? (profile.measured.method == PPCP_MEAS_SUSTAINED ? .sustained : .coldSample)
                : nil)
    }

    /// ⚠ A function rather than a `switch` expression inside a ternary: Swift 6
    /// permits a `switch` expression only in a `return`, a `throw` or the source
    /// of an assignment, and the nested form reads worse anyway.
    ///
    /// ⛔ `has_intrinsics == false` is **absent**, not `none`. `CORE` 5.11m makes
    /// `intrinsics: none` a positive declaration a preview profile makes; I19
    /// makes the field mandatory on a camera profile. Collapsing the two would
    /// turn "this Source is not a camera" into "this camera delivers no
    /// intrinsics", which is a claim about a camera.
    private static func intrinsicsView(_ profile: ppcp_capture_profile) -> Intrinsics? {
        guard profile.has_intrinsics else { return nil }
        switch profile.intrinsics {
        case PPCP_INTR_PER_FRAME: return .perFrame
        case PPCP_INTR_FIXED: return .fixed
        default: return Intrinsics.none
        }
    }

    private static func provenance(_ p: ppcp_provenance) -> PpcpProvenance {
        switch p {
        case PPCP_PROV_VENDOR: .vendor
        case PPCP_PROV_MEASURED: .measured
        default: .assumed
        }
    }

    /// A `ppcp_id` is a NUL-terminated `char[65]` with a length beside it; the
    /// NUL "is not part of the identifier and is never encoded" (`common.h`).
    private static func text(_ id: ppcp_id) -> String {
        var value = id
        return withUnsafeBytes(of: &value.v) { raw in
            String(decoding: raw.prefix(Int(id.len)), as: UTF8.self)
        }
    }

    // MARK: Planning

    private struct ProfilePlan {
        let id: String
        let timing: ppcp_timing
        let camera: (geometry: ppcp_geometry, intrinsics: ppcp_intrinsics_mode)?
        let format: (codec: String, width: UInt32, height: UInt32, pixelFormat: String)?
        let rate: Int64?
        let optical: (exposure: ClosedRange<Int64>, iso: ClosedRange<Int64>)?
        let measured: ppcp_measured_capability?

        func build(into out: UnsafeMutablePointer<ppcp_capture_profile>) throws {
            var timing = timing
            try check(ppcp_capture_profile_make(out, id, &timing))
            if let camera {
                var geometry = camera.geometry
                try check(ppcp_capture_profile_set_camera(out, &geometry, camera.intrinsics))
            }
            if let format {
                try check(ppcp_capture_profile_set_format(out, format.codec, format.width,
                                                          format.height, format.pixelFormat))
            }
            if let rate {
                // ⚠ `nominal == min == max`, and it is honest rather than lazy: a
                // CaptureProfile is *a mode a Source can operate in* (5.7), and
                // `warmUp` pins both `activeVideoMinFrameDuration` and
                // `activeVideoMaxFrameDuration` to exactly this rate precisely so
                // the device cannot drop below it without reporting (REQ-CAP-3).
                // Declaring a min the app has forbidden itself to use would be a
                // capability this peer will never exhibit.
                try check(ppcp_capture_profile_set_rate(out, rate, rate, rate))
            }
            if let optical {
                try check(ppcp_capture_profile_set_optical(out, optical.exposure.lowerBound,
                                                           optical.exposure.upperBound,
                                                           optical.iso.lowerBound,
                                                           optical.iso.upperBound))
            }
            if var measured {
                // ⛔ I28/5.8a. Reached only from a real self-test; there is no
                // path to here from the profile's own claimed values, from
                // `DeviceProfiles.json`, or from another device model — see
                // `measuredCapability(from:)`.
                try check(ppcp_capture_profile_set_measured(out, &measured))
            }
        }
    }

    private struct SourcePlan {
        let id: String
        let kind: String
        let timebaseId: String
        let physical: Bool
        let optics: String?
        let label: String?
        let viewpoint: PpcpViewpoint?
        let profiles: [ProfilePlan]
    }

    private static func plan(_ input: PpcpDeclarationInput) throws -> [SourcePlan] {
        var plans: [SourcePlan] = []

        // ── One Source per PHYSICAL lens (5.6d) ───────────────────────────────
        //
        // ⛔ 5.6d: "A physically distinct lens is a distinct Source. A peer MUST
        // NOT present two lenses as one Source, and `optics` names which one …
        // a device offering the same profile on both a wide and an ultra-wide
        // lens makes that ambiguity real." Which is exactly this device: current
        // iPhones offer the *same* 1080p240 on the wide and the ultra-wide, and
        // a consumer that could not tell which produced a bundle could not
        // interpret its calibration. REQ-OPT-5 already refuses virtual
        // multi-lens devices, so `physical` is `true` here and 5.6b never
        // applies — but it is passed explicitly rather than defaulted, because a
        // future `.builtInTripleCamera` would have to come through this line.
        for lens in input.capability.availableLenses where lens != .unknown {
            let modes = input.capability.claimed.filter { $0.lens == lens }
            guard modes.isEmpty == false else { continue }
            plans.append(SourcePlan(
                id: "src:camera:\(Self.optics(for: lens))",
                kind: "camera",
                timebaseId: input.captureTimebaseId,
                physical: true,
                optics: Self.optics(for: lens),
                label: lens.displayName,
                viewpoint: input.viewpoint,
                profiles: try modes
                    .sorted { ($0.height, $0.fps) > ($1.height, $1.fps) }
                    .map { try cameraProfile($0, input: input) }))
        }
        guard plans.isEmpty == false else { throw PpcpDeclarationError.noCameraSource }

        // ── The microphone, on the SAME timebase (I4) ─────────────────────────
        //
        // ⛔ **The same `Timebase.id` string, not a relation.** `CORE` §5.3: "On
        // iOS, camera and microphone Sources both reference `tb:hosttime` and no
        // relation exists because none is needed." This is a *checkable claim*
        // about the platform and not a convenience: an Android device reporting
        // `SENSOR_INFO_TIMESTAMP_SOURCE == UNKNOWN` must declare two ids and a
        // relation, "and there is no third option and no silent default". A port
        // that copied this line without re-checking would be making the exact
        // silent assumption of zero that §5.3 exists to prevent.
        //
        // ⚠ `convention: mid` and no `format`. A microphone sample is an instant,
        // not a frame with an exposure, so `nominal_frame_start` has nothing to
        // offset from and I22 forbids the offset field outright. D5 depends on
        // this: `CORE` 5.12 has an acoustic Candidate's `at` be "the raw instant
        // after `tof_correction`" precisely *because* the convention is `mid`.
        if input.declaresMicrophone {
            plans.append(SourcePlan(
                id: "src:microphone",
                kind: "microphone",
                timebaseId: input.captureTimebaseId,
                physical: true,
                optics: nil,
                label: "Built-in microphone",
                viewpoint: nil,
                profiles: [try nonCameraProfile(id: "default")]))
        }

        // ── The IMU ──────────────────────────────────────────────────────────
        //
        // ⚠ Also `mid`, for the same reason, and also on `tb:hosttime`:
        // CoreMotion stamps with the same host clock. No `rate`, because the
        // delivered interval is a request the platform may not honour and a
        // nominal rate this peer has not measured is not a declaration
        // (5.1: "absence never means zero").
        if input.declaresIMU {
            plans.append(SourcePlan(
                id: "src:imu",
                kind: "imu",
                timebaseId: input.captureTimebaseId,
                physical: true,
                optics: nil,
                label: "Device motion",
                viewpoint: nil,
                profiles: [try nonCameraProfile(id: "default")]))
        }

        return plans
    }

    /// `CORE` 5.6 `optics` — an open-registry `Kind`, in the protocol's spelling
    /// rather than the platform's.
    private static func optics(for lens: Lens) -> String {
        switch lens {
        case .wide: "wide"
        case .ultraWide: "ultra_wide"
        case .telephoto: "telephoto"
        case .unknown: "unknown"
        }
    }

    private static func cameraProfile(_ mode: VideoMode,
                                      input: PpcpDeclarationInput) throws -> ProfilePlan {
        // ── Timing (5.7a, 5.7b; I22, I31) ────────────────────────────────────
        //
        // ⛔ `nominal_frame_start` is "what **every AVFoundation source
        // declares**" (5.7), so it is the convention for the whole mobile side,
        // and the constructor that takes it **requires** the offset and its
        // provenance. There is no way to reach a defaulted zero from here: the
        // other constructor refuses `nominal_frame_start` outright. That is
        // CT-I22's "a defaulted zero is not producible", held by the API.
        //
        // ⚠ The value is 0 and the provenance is `assumed`, from
        // `DeviceProfiles.json` (A13), and it will stay `assumed` until an LED
        // timecode rig exists (A12, REQ-TEST-1/2). 5.7b is explicit about why the
        // zero is still declared: "a declared zero is a checkable claim; an
        // omitted field is not — but a declared zero with no provenance is
        // indistinguishable from an unmeasured one."
        var timing = ppcp_timing()
        try check(ppcp_timing_make_nominal_frame_start(
            &timing,
            input.timing.frameStartToExposureOffsetNs,
            cProvenance(input.timing.offsetProvenance)))
        if let sigma = input.timing.offsetSigmaNs {
            try check(ppcp_timing_set_offset_sigma(&timing, sigma))
        }

        // ── Geometry (5.7e; 6.2b) ────────────────────────────────────────────
        var geometry = ppcp_geometry()
        if let entry = input.timing.geometryEntry(width: mode.width, height: mode.height,
                                                  fps: mode.fps),
           let readoutNs = entry.readout.readoutNs(rateMillihertz: mode.rateMillihertz) {
            try check(ppcp_geometry_make_rolling_shutter(
                &geometry, readoutNs, cProvenance(entry.readout.provenance),
                entry.direction == .topToBottom ? PPCP_ROLL_TOP_TO_BOTTOM
                                                : PPCP_ROLL_BOTTOM_TO_TOP,
                // 6.2b — "rows in the delivered image, R", which is the format's
                // own height unless the model's data says otherwise.
                UInt32(entry.rows ?? mode.height)))
        } else {
            // ⛔ **Not a fallback to `global`, and not a fallback to a number.**
            // A model with no geometry entry at all is a model whose data file
            // has not been filled in, and declaring `global` for a rolling sensor
            // would be a false claim of the most damaging kind — I31's whole
            // subject is that a wrong timing constant "silently biases every
            // cross-source comparison the host makes, in a way that moves with
            // exposure and therefore looks like clock drift". Refusing to build
            // the declaration is the honest failure, and it fails at onboarding
            // on a developer's desk rather than at a range.
            throw PpcpDeclarationError.noGeometryForProfile(mode.id)
        }

        return ProfilePlan(
            id: "\(mode.width)x\(mode.height)@\(VideoMode.fpsText(mode.fps))",
            timing: timing,
            // ⚠ `per_frame`, and it is a claim this application keeps: `warmUp`
            // sets `isCameraIntrinsicMatrixDeliveryEnabled` (REQ-OPT-7) and
            // turns stabilisation off, which that delivery requires anyway
            // (REQ-OPT-1). `VideoMode.deliversIntrinsics` is `false` at
            // *enumeration* because it is a property of a live
            // `AVCaptureConnection` and not of a format — it is not evidence
            // against the claim.
            camera: (geometry, PPCP_INTR_PER_FRAME),
            format: mode.pixelFormat.map {
                // ⚠ **A reported ambiguity.** `CORE` 5.7 gives `format` as
                // `{ codec, width, height, pixel_format }` without saying whether
                // `codec` describes what the *Source delivers* — uncompressed
                // samples, on this platform — or what the *Capture payload* is
                // encoded as. They differ here: the video data output hands over
                // `pixel_format` buffers and the clip is written as
                // `clipCodec`. The receiving end cares about the second, so that
                // is what is declared, with the first carried beside it.
                (codec: input.clipCodec, width: UInt32(mode.width),
                 height: UInt32(mode.height), pixelFormat: $0)
            },
            rate: mode.rateMillihertz,
            optical: mode.exposureRangeNs.flatMap { exposure in
                mode.isoRange.map { (exposure, $0) }
            },
            measured: try measuredCapability(from: input.capability.measured, for: mode,
                                             timebaseId: input.captureTimebaseId))
    }

    /// A profile for a Source that is not a camera: `timing` only.
    ///
    /// ⚠ 5.6a and I19 require `geometry` and `intrinsics` on a **camera** Source's
    /// profiles; a microphone has neither and declaring `global` geometry on one
    /// would be meaningless rather than merely wrong. `timing` is required of
    /// every profile whatever the Source is, and it is present.
    private static func nonCameraProfile(id: String) throws -> ProfilePlan {
        var timing = ppcp_timing()
        try check(ppcp_timing_make(&timing, PPCP_CONV_MID))
        return ProfilePlan(id: id, timing: timing, camera: nil, format: nil,
                           rate: nil, optical: nil, measured: nil)
    }

    /// `CORE` 5.8a / I28 — the only route from a self-test to a `measured` block.
    ///
    /// ⛔ **Three refusals, and each closes a way of synthesising one.** It
    /// returns `nil` when there is no self-test at all (5.8a: "absence means not
    /// measured"); `nil` when the self-test was of a *different* profile (5.8c:
    /// "1080p240 and 1080p120 are separate self-tests with separate results");
    /// and `nil` when the run has no `observed_at` in the capture timebase,
    /// because an `Instant` without a `tb` does not exist (I1) and inventing one
    /// from the wall clock would breach 5.3b as well.
    ///
    /// `method` comes from the caller and cannot be defaulted — 5.8b, and the
    /// specification's own diagnosis that "without `method` the cold number
    /// quietly becomes the displayed one".
    private static func measuredCapability(from measured: MeasuredCapability?,
                                           for mode: VideoMode,
                                           timebaseId: String) throws
        -> ppcp_measured_capability? {
        guard let measured, measured.mode.id == mode.id,
              let observedNs = measured.observedHostTimeNs else { return nil }

        var observedAt = ppcp_instant()
        try check(ppcp_instant_make_z(&observedAt, timebaseId, observedNs))

        var out = ppcp_measured_capability()
        try check(ppcp_measured_capability_make(
            &out,
            measured.method == .sustained ? PPCP_MEAS_SUSTAINED : PPCP_MEAS_COLD_SAMPLE,
            Int64((measured.durationSeconds * 1_000_000_000).rounded()),
            measured.sustainedRateMillihertz,
            Int64(measured.droppedFrames),
            &observedAt))
        out.has_thermal_at_end = true
        out.thermal_at_end = cThermal(measured.thermalAtEnd)
        // ⛔ `noise_figure` is left absent. 5.7/5.8: "absent means not measured",
        // and REQ-CAP-4's optical bar needs a measured noise figure no device has
        // yet. A plausible number here would be exactly I31's defect wearing
        // I28's clothes.
        try check(ppcp_measured_capability_validate(&out))
        return out
    }

    private static func cProvenance(_ provenance: PpcpProvenance) -> ppcp_provenance {
        switch provenance {
        case .assumed: PPCP_PROV_ASSUMED
        case .vendor: PPCP_PROV_VENDOR
        case .measured: PPCP_PROV_MEASURED
        }
    }

    /// `CORE` 5.8 — "an ordinal protocol vocabulary, not a platform passthrough",
    /// with the iOS mapping the specification tabulates. ⚠ `.fair` maps to
    /// `elevated`, not to `nominal`: the names differ and the table is the
    /// authority.
    private static func cThermal(_ state: ThermalState) -> ppcp_thermal_level {
        switch state {
        case .nominal: PPCP_THERMAL_NOMINAL
        case .fair: PPCP_THERMAL_ELEVATED
        case .serious: PPCP_THERMAL_SERIOUS
        case .critical: PPCP_THERMAL_CRITICAL
        }
    }
}

// MARK: - Failure

public enum PpcpDeclarationError: Error, Sendable, Equatable {
    /// `CORE` 5.6d — a capture peer with no physical lens has nothing to declare.
    case noCameraSource
    /// A13/REQ-PORT-10 — the model's `DeviceProfiles.json` entry carries no
    /// geometry for this profile, and one will not be invented (I31).
    case noGeometryForProfile(String)
}
