# PinPointCapture — build, test and deploy.
#
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored.
# Run `make gen` after pulling, after adding files, or whenever the project
# looks stale. Never edit the project file by hand.

SCHEME      := PinPointCapture
PROJECT     := PinPointCapture.xcodeproj
APP         := PinPointCapture.app
BUNDLE_ID   := org.pinpointstudio.capture
CONFIG      ?= Debug
DERIVED     := build
# ⚠ Resolved at run time, not hardcoded. The installed simulator set changes
# with every Xcode release — an iOS 27 runtime ships iPhone 17s and no 16.
SIM_NAME    ?= $(shell xcrun simctl list devices available 2>/dev/null \
                 | grep -oE 'iPhone [0-9]+( Pro)?' | head -1)
SIM_DEST    ?= generic/platform=iOS Simulator
TEST_DEST   ?= platform=iOS Simulator,name=$(SIM_NAME)
DEV_DEST    ?= generic/platform=iOS
XCB         := xcbeautify --quieter
DEVICE_APP  := $(DERIVED)/Build/Products/$(CONFIG)-iphoneos/$(APP)

.PHONY: all gen build build-device _udid test test-core test-app device deploy lint clean help

all: build

help:
	@echo "gen           regenerate $(PROJECT) from project.yml"
	@echo "build         build for the simulator"
	@echo "build-device  build for a physical device (needs signing)"
	@echo "test          run the unit tests"
	@echo "device        list connected devices"
	@echo "deploy        gen + build-device + install + launch on a connected device"
	@echo "lint          run swiftlint"
	@echo "clean         remove generated project and build products"

gen:
	@xcodegen generate --quiet
	@echo "generated $(PROJECT)"

$(PROJECT):
	@$(MAKE) --no-print-directory gen

# ⚠ Depends on `gen`, not on $(PROJECT). project.yml globs Sources/, so adding a
# new file leaves project.yml untouched and a timestamp rule would rebuild a
# stale project that omits it — surfacing as "cannot find X in scope".
# xcodegen takes well under a second; correctness is worth more than that.
build: gen
	set -o pipefail && xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(SIM_DEST)' \
		-derivedDataPath $(DERIVED) \
		| $(XCB)

# ⚠ Builds against the CONNECTED device by UDID, not against a generic iOS
# destination. Automatic signing has to name a specific device to include it in a
# provisioning profile; with `generic/platform=iOS` it cannot, and fails with the
# misleading "Your team has no devices" rather than naming the phone.
# Override with:  make build-device UDID=<udid>
build-device: gen
	@set -e; \
	udid="$(UDID)"; \
	if [ -z "$$udid" ]; then udid=$$($(MAKE) --no-print-directory _udid); fi; \
	if [ -z "$$udid" ]; then \
		echo "make build-device: no connected device. Try: make device"; exit 1; \
	fi; \
	echo "device UDID: $$udid"; \
	set -o pipefail && xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination "id=$$udid" \
		-derivedDataPath $(DERIVED) \
		-allowProvisioningUpdates \
		| $(XCB)

# Resolve the UDID of the first connected physical device. Prints nothing if none.
_udid:
	@tmp=$$(mktemp -t ppcp-devices); \
	xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
	python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
c=[x for x in d if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print(c[0]["hardwareProperties"]["udid"] if c else "")' "$$tmp" 2>/dev/null || true; \
	rm -f "$$tmp"

# Everything. Core first: it is the fast one, and if the layer seam is broken
# there is no point booting a simulator to find out.
test: test-core test-app

# ⚠ The one to reach for. Runs natively on the host in milliseconds — no
# simulator, no runtime download, no Xcode. Includes the layer purity gate that
# fails the build if Core imports a platform framework (REQ-PORT-3).
test-core:
	@cd Packages/Core && swift test

test-app: gen
	@if ! xcrun simctl list runtimes 2>/dev/null | grep -q 'iOS'; then \
		echo "make test-app: no iOS simulator runtime is installed."; \
		echo "  Run: xcodebuild -downloadPlatform iOS"; \
		echo "  (make test-core needs no simulator and covers the Core layer.)"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make test-app: no available iPhone simulator found."; exit 1; \
	fi
	@echo "simulator: $(SIM_NAME)"
	@# ⚠ NOT piped through `xcbeautify --quieter`, which swallows swift-testing's
	@# output entirely and leaves only XCTest's "Executed 0 tests" summary — so a
	@# passing suite looks like an empty one. Filter to the result lines instead.
	set -o pipefail && xcodebuild test \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		| grep -E '^(◇|✔|✘)|error:|Test run|\*\* TEST' || \
		(echo "make test-app: no test output — see the xcresult bundle"; exit 1)

device:
	@xcrun devicectl list devices

# Resolve the first connected device, or explain plainly why we cannot continue.
# Set DEVICE=<identifier> to pin a specific one.
deploy: gen
	@set -e; \
	dev="$(DEVICE)"; \
	if [ -z "$$dev" ]; then \
		tmp=$$(mktemp -t ppcp-devices); \
		xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
		dev=$$(python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
c=[x for x in d if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print(c[0]["identifier"] if c else "")' "$$tmp" 2>/dev/null || echo ""); \
		rm -f "$$tmp"; \
	fi; \
	if [ -z "$$dev" ]; then \
		echo ""; \
		echo "make deploy: no connected device."; \
		echo ""; \
		echo "  Plug an iPhone or iPad in over USB, unlock it, and trust this Mac."; \
		echo "  Check what the Mac can see with:  make device"; \
		echo "  Then pin one explicitly if needed: make deploy DEVICE=<identifier>"; \
		echo ""; \
		exit 1; \
	fi; \
	echo "device: $$dev"; \
	$(MAKE) --no-print-directory build-device; \
	if [ ! -d "$(DEVICE_APP)" ]; then \
		echo "make deploy: $(DEVICE_APP) was not produced by the device build."; \
		exit 1; \
	fi; \
	xcrun devicectl device install app --device "$$dev" "$(DEVICE_APP)"; \
	xcrun devicectl device process launch --device "$$dev" --terminate-existing $(BUNDLE_ID)

lint:
	@swiftlint lint --quiet

clean:
	@rm -rf $(DERIVED) $(PROJECT)
	@echo "cleaned"
