# PinPointCapture — build, test and deploy.
#
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored.
# Run `make gen` after pulling, after adding files, or whenever the project
# looks stale. Never edit the project file by hand.

SCHEME      := PinPointCapture
PROJECT     := PinPointCapture.xcodeproj
APP         := PinPointCapture.app
BUNDLE_ID   := org.pinpointstudio.capture
CONFIG      ?= Debug
DERIVED     := build
# ⚠ Resolved at run time, not hardcoded. The installed simulator set changes
# with every Xcode release — an iOS 27 runtime ships iPhone 17s and no 16.
SIM_NAME    ?= $(shell xcrun simctl list devices available 2>/dev/null \
                 | grep -oE 'iPhone [0-9]+( Pro)?' | head -1)
SIM_DEST    ?= generic/platform=iOS Simulator
TEST_DEST   ?= platform=iOS Simulator,name=$(SIM_NAME)
DEV_DEST    ?= generic/platform=iOS
XCB         := xcbeautify --quieter
DEVICE_APP  := $(DERIVED)/Build/Products/$(CONFIG)-iphoneos/$(APP)

# ⚠ **Every build is capped at three jobs, and it is not a preference.** This is
# a 16 GB machine and an unbounded `xcodebuild` alongside a `swift build` took it
# down on 22 August 2026. `-jobs`/`-j` here rather than in each recipe so a new
# target cannot forget.
JOBS        := 3

# ⛔ **A WALL-CLOCK CEILING ON EVERY UNATTENDED xcodebuild.** On 24 August 2026 a
# hung test held `xcodebuild` for 25 minutes at 0% CPU. Nothing killed it:
# `-default-test-execution-time-allowance 120` and `-maximum-test-execution-time-
# allowance 300` are both set below and **neither fired** — they do not apply to a
# hang inside a Swift Testing async case, which is precisely what hung. It was
# noticed only because someone happened to be watching, and **a hang reads as
# "still running", so nothing about it looks wrong.**
#
# ⚠ macOS ships no `timeout(1)`. `perl -e 'alarm shift; exec @ARGV'` is the
# portable equivalent: the alarm survives `exec`, so the timer belongs to
# xcodebuild itself rather than to a wrapper it could outlive. Exit status is
# 142 (128 + SIGALRM).
#
# Sizing, from the run of 2026-08-24 (`Test-PinPointCapture-2026.08.24_17-56-33`):
# 74 cases, **median 0.001s**, slowest **14.0s**, whole suite ~55s. The ceiling is
# an order of magnitude above that on purpose — it is a backstop against a hang,
# not a performance budget, and it must never fire on a slow-but-honest machine.
GUARD        := /usr/bin/perl -e 'alarm shift; exec @ARGV'
GUARD_STATUS := 142
TEST_TIMEOUT_S  ?= 600
BUILD_TIMEOUT_S ?= 600

# `libppcp`'s conformance tools. A sibling checkout during co-development.
LIBPPCP     ?= ../libppcp
PPCP_SIM    ?= $(LIBPPCP)/build/dev/tools/ppcp-sim/ppcp-sim
PPCP_CONFORM ?= $(LIBPPCP)/build/dev/tools/ppcp-conform/ppcp-conform
# ⚠ **Two axes, and keeping them apart is the point of `tools/scenarios`.** What
# the peer IS is a declaration file; what it DOES is a named scenario. "A host
# that never answers a Candidate" is `SCENARIO=silent-host` over the *reference*
# host declaration — deriving the file name from the scenario looked tidy and
# broke the moment the two differed.
SCENARIO    ?= reference-host
DECL        ?= reference-host
SCENARIO_DECL ?= $(LIBPPCP)/tools/scenarios/$(DECL).json
# ⚠ **Which `CONF` §5 interoperability row this run is.** `ppcp-sim` serves one
# link, so a suite where several tests dialled the same listener would have all
# but one measuring a peer that had already finished. `ROW` picks exactly one;
# `d9` (the default) is the CT-S5 device row that has always been there.
ROW         ?= d9
# What `ppcp-sim` is told to expect of ITSELF, on top of seeing no violation.
# A row's assertions live on both sides: this is the far end's half.
EXPECT      ?= violations=0
# ⚠ Long enough for a simulator to install and run, and no longer — the target
# `wait`s for ppcp-sim so it can read the exit code its `--expect` produces, so
# this number is also how long `make conform` takes after the test has passed.
# The device side's own deadline is `ConformanceHarness.run(seconds:)`.
CONFORM_RUN_MS ?= 45000

# ⛔ **The claim** (`CONF` 1a): a conformance run without a profile set is not a
# claim. This is the set `docs/conformance/ppcp-conformance.md` §1 states, and the two must
# not drift — a row that passes against a set this application does not claim is
# measuring somebody else.
CONFORM_PROFILES ?= core,capture,detect,mint,live,offline,markup
CONFORM_OUT      ?= docs/conformance
# IOP-3 / IOP-10 — the bundles PinPointStudio imports. Small, and checked in.
BUNDLE_OUT       ?= docs/conformance/bundles
# How long the simulator gets to boot, install and reach the dial loop before
# `ppcp-conform` starts binding ports. ⚠ Generous on purpose: a row lost to a
# slow boot is a FAILED row, and there is no way to tell that apart from a real
# refusal afterwards.
CONFORM_WARMUP_S ?= 75

COMMA := ,

.PHONY: all gen build build-device _udid _udid_paired test test-core test-app conform conform-sim conform-tool conform-iop interop read-bundle pull-bundles device deploy lint clean help

# ⚠ **Two instruments, one target.** `make conform` runs `ppcp-conform`, which is
# what fills the matrix column (plan A11). `make conform SCENARIO=<name>` keeps
# the direct `ppcp-sim` path, which is how a single scenario is driven while
# debugging one. `$(origin ...)` is what tells an explicit SCENARIO from the
# default sitting in this file.
ifeq ($(origin SCENARIO),command line)
conform: conform-sim
else
conform: conform-tool
endif

all: build

help:
	@echo "gen           regenerate $(PROJECT) from project.yml"
	@echo "build         build for the simulator"
	@echo "build-device  build for a physical device (needs signing)"
	@echo "test          run the unit tests"
	@echo "conform       ppcp-conform drives the device (D9); SCENARIO=<n> for one ppcp-sim row"
	@echo "              CONF §5 rows:  make conform ROW=iop1|iop2 SCENARIO=... DECL=..."
	@echo "pull-bundles  copy the bundles an IOP-1 run wrote out of the simulator container"
	@echo "read-bundle   read a bundle another implementation wrote: FILE=<path.ppcpbndl>"
	@echo "interop       wave 2: dial the REAL PinPointStudio TLS listeners (HOST=, HOST2=, PSK=, IDENTITY=)"
	@echo "device        list connected devices"
	@echo "deploy        gen + build-device + install + launch on a connected device"
	@echo "lint          run swiftlint"
	@echo "clean         remove generated project and build products"

gen:
	@xcodegen generate --quiet
	@echo "generated $(PROJECT)"

$(PROJECT):
	@$(MAKE) --no-print-directory gen

# ⚠ Depends on `gen`, not on $(PROJECT). project.yml globs Sources/, so adding a
# new file leaves project.yml untouched and a timestamp rule would rebuild a
# stale project that omits it — surfacing as "cannot find X in scope".
# xcodegen takes well under a second; correctness is worth more than that.
build: gen
	set -o pipefail && $(GUARD) $(BUILD_TIMEOUT_S) xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(SIM_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)

# ⚠ Builds against the CONNECTED device by UDID, not against a generic iOS
# destination. Automatic signing has to name a specific device to include it in a
# provisioning profile; with `generic/platform=iOS` it cannot, and fails with the
# misleading "Your team has no devices" rather than naming the phone.
# Override with:  make build-device UDID=<udid>
build-device: gen
	@set -e; \
	udid="$(UDID)"; \
	if [ -z "$$udid" ]; then udid=$$($(MAKE) --no-print-directory _udid); fi; \
	if [ -z "$$udid" ]; then \
		echo "make build-device: no paired PHYSICAL device."; \
		paired=$$($(MAKE) --no-print-directory _udid_paired); \
		if [ -n "$$paired" ]; then \
			echo "  seen but not usable: $$paired"; \
			echo "  plug it in, unlock it, and trust this Mac."; \
		fi; \
		echo "  ⛔ a simulator is NOT a substitute here — see the _udid note."; \
		exit 1; \
	fi; \
	echo "device UDID: $$udid"; \
	set -o pipefail && xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination "id=$$udid" \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		-allowProvisioningUpdates \
		| $(XCB)

# Resolve the UDID of the first connected PHYSICAL device. Prints nothing if none.
#
# ⛔ **`devicectl list devices` lists simulators too, and they report
# `tunnelState: connected` while a real phone sitting on the desk reports
# `disconnected`.** Filtering on tunnelState alone therefore returns a SIMULATOR
# udid — which `xcodebuild -destination id=...` accepts happily, so `make
# build-device` and `make deploy` succeed against a simulator and every "device
# run" measures a machine with no camera. Found 24 Aug 2026 while setting up
# E1.1's device run; it had been silently true since this target was written.
#
# ⚠ **Filter on `reality` and `pairingState`, NOT on `tunnelState`.** The tunnel
# to a wired device is established per-operation and torn down when idle, so
# `list devices` reports `tunnelState: disconnected` for a phone that is plugged
# in, unlocked and perfectly usable — `devicectl device info details` on the same
# device brings the tunnel up and reports `connected` a second later. Filtering on
# it rejected the phone all of 24 August, which is the second bug in this one
# resolver in a day: it first returned a SIMULATOR, and then nothing at all.
_udid:
	@tmp=$$(mktemp -t ppcp-devices); \
	xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
	python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
p=[x for x in d if x.get("hardwareProperties",{}).get("reality")=="physical"\
   and x.get("connectionProperties",{}).get("pairingState")=="paired"];\
c=[x for x in p if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print((c or p)[0]["hardwareProperties"]["udid"] if p else "")' "$$tmp" 2>/dev/null || true; \
	rm -f "$$tmp"

# Physical devices that are paired but NOT connected, for a useful error message.
_udid_paired:
	@tmp=$$(mktemp -t ppcp-devices); \
	xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
	python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
p=[x for x in d if x.get("hardwareProperties",{}).get("reality")=="physical"];\
print("; ".join(x.get("deviceProperties",{}).get("name","?")+" ("+x.get("connectionProperties",{}).get("tunnelState","?")+")" for x in p))' "$$tmp" 2>/dev/null || true; \
	rm -f "$$tmp"

# Everything. Core first: it is the fast one, and if the layer seam is broken
# there is no point booting a simulator to find out.
test: test-core test-app

# ⚠ The one to reach for. Runs natively on the host in milliseconds — no
# simulator, no runtime download, no Xcode. Includes the layer purity gate that
# fails the build if Core imports a platform framework (REQ-PORT-3).
test-core:
	@cd Packages/Core && swift test -j $(JOBS)

test-app: gen
	@if ! xcrun simctl list runtimes 2>/dev/null | grep -q 'iOS'; then \
		echo "make test-app: no iOS simulator runtime is installed."; \
		echo "  Run: xcodebuild -downloadPlatform iOS"; \
		echo "  (make test-core needs no simulator and covers the Core layer.)"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make test-app: no available iPhone simulator found."; exit 1; \
	fi
	@echo "simulator: $(SIM_NAME)"
	@# ⚠ `↳` is in the filter because swift-testing prefixes the CONTINUATION
	@# lines of a multi-line assertion message with it. Without it the failure
	@# name survives and the transcript attached to it does not — which is
	@# exactly what was thrown away the one time it was wanted (D9, CT-S4 (6)).
	@# ⚠ NOT piped through `xcbeautify --quieter`, which swallows swift-testing's
	@# output entirely and leaves only XCTest's "Executed 0 tests" summary — so a
	@# passing suite looks like an empty one. Filter to the result lines instead.
	@# ⚠ The two allowances below are kept because they catch a SLOW test, but
	@# they did NOT catch a HUNG one on 2026-08-24 — $(GUARD) is what does.
	@# ⚠ xcodebuild's status is written to a FILE, not read from the pipeline.
	@# `set -o pipefail` reports the RIGHTMOST non-zero status, and `grep` exits 1
	@# when a killed xcodebuild printed nothing to match — so the timeout's 142 is
	@# masked by grep's 1 and a hang reports itself as "no test output". Measured
	@# while adding this guard, which is exactly the class of bug it exists for.
	@set -o pipefail; \
	mkdir -p $(DERIVED); rm -f $(DERIVED)/.xcodebuild-status; \
	{ $(GUARD) $(TEST_TIMEOUT_S) xcodebuild test \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		-default-test-execution-time-allowance 120 \
		-maximum-test-execution-time-allowance 300 \
		; echo $$? > $(DERIVED)/.xcodebuild-status; } \
		| grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST'; \
	status=$$(cat $(DERIVED)/.xcodebuild-status 2>/dev/null || echo 1); \
	if [ $$status -eq $(GUARD_STATUS) ]; then \
		echo ""; \
		echo "make test-app: TIMED OUT after $(TEST_TIMEOUT_S)s and was killed."; \
		echo "  This suite runs in ~55s (74 cases, median 1ms, slowest 14s), so this"; \
		echo "  is a hang, not a slow machine. The last test named above is where it"; \
		echo "  stopped — a hang prints its start line and never its result."; \
		echo "  Raise the ceiling with: make test-app TEST_TIMEOUT_S=<seconds>"; \
		exit 1; \
	elif [ $$status -ne 0 ]; then \
		echo "make test-app: no test output — see the xcresult bundle"; \
		exit 1; \
	fi

# D9 — the device peer driven by a counterpart this repository did not write.
#
# ⚠ `ppcp-conform` (libppcp L14) is what this will call once it exists; until
# then it drives `ppcp-sim` directly, which is the same transport and the same
# refusals. The target switches on its own when the binary appears.
#
# ⛔ The simulator peer is started BEFORE the test and killed after, whatever
# happens: a listener left bound holds the port and the next run fails for a
# reason that has nothing to do with conformance.
conform-sim: gen
	@if [ ! -x "$(PPCP_SIM)" ]; then \
		echo "make conform: no ppcp-sim at $(PPCP_SIM)"; \
		echo "  Build it:  cmake --build $(LIBPPCP)/build/dev --target ppcp-sim"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make conform: no available iPhone simulator found."; exit 1; \
	fi
	@# ⛔ **Build first, then start the counterpart.** The first version started
	@# ppcp-sim and then ran `xcodebuild test`, which builds — and a compile is
	@# minutes while `--run-ms` is seconds, so the simulator peer had exited before
	@# the device dialled and the failure looked like a refused connection.
	@# `build-for-testing` / `test-without-building` is what makes the window the
	@# test's rather than the compiler's.
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	portfile=$$(mktemp -t ppcp-conform-port); \
	log=$$(mktemp -t ppcp-conform-log); \
	"$(PPCP_SIM)" --role host --listen 0 --port-file "$$portfile" \
		--declaration "$(SCENARIO_DECL)" --scenario $(SCENARIO) \
		$(foreach e,$(subst $(COMMA), ,$(EXPECT)),--expect $(e)) \
		--run-ms $(CONFORM_RUN_MS) >"$$log" 2>&1 & \
	simpid=$$!; \
	trap 'kill $$simpid 2>/dev/null || true' EXIT; \
	for i in 1 2 3 4 5 6 7 8 9 10; do \
		[ -s "$$portfile" ] && break; sleep 0.2; \
	done; \
	port=$$(cat "$$portfile" 2>/dev/null); \
	if [ -z "$$port" ]; then echo "make conform: ppcp-sim never reported a port"; \
		cat "$$log"; exit 1; fi; \
	echo "ppcp-sim listening on $$port, scenario $(SCENARIO)"; \
	set -o pipefail; \
	TEST_RUNNER_PPCP_CONFORM_PORT=$$port \
	TEST_RUNNER_PPCP_CONFORM_ROW=$(ROW) \
	TEST_RUNNER_PPCP_CONFORM_SCENARIO=$(SCENARIO) xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:PinPointCaptureTests/ConformanceHarnessTests \
		-default-test-execution-time-allowance 120 \
		-maximum-test-execution-time-allowance 300 \
		| grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' \
		|| { echo "--- ppcp-sim ---"; cat "$$log"; exit 1; }; \
	wait $$simpid || { echo "--- ppcp-sim ---"; cat "$$log"; \
		echo "make conform: ppcp-sim exited non-zero — a violation or an unmet expectation"; \
		exit 1; }; \
	echo "--- ppcp-sim ---"; cat "$$log"

# D9's claim — `ppcp-conform` drives this device through every applicable row of
# `PPCP-CONF` §3 and §4 and emits the matrix fragment.
#
# ⚠ **`--listen`, not `--connect`.** The device DIALS: `PpcpDirectConnector` is a
# connector and there is no plaintext listener anywhere in the app, which is also
# how `RV` 2c1's "nothing to accept on" stays easy to hold. The tool spawns one
# `ppcp-sim` per row, sequentially, on that one port — so the device dials once
# per row, which is what `ConformanceHarnessTests.ppcpConformDrivesTheDevice()`
# does.
#
# ⛔ **THE SIMULATOR STARTS FIRST, AND THEN THE TOOL.** `ppcp-conform` gives each
# row 5–8 s and moves on; a simulator takes tens of seconds to boot, install and
# launch. Starting the tool first burned every row waiting for a device that was
# still starting up — all four failed "timed out waiting for two bound channels",
# which is the same mistake as starting the counterpart before the build, one
# layer further in. So the test is launched, `CONFORM_WARMUP_S` is allowed for it
# to reach its dial loop, and only then does the tool begin binding ports.
#
# ⛔ **The verdict is the tool's exit code, not the test's.** 0 every applicable
# row passed, 1 a row failed, 2 a bad invocation, 3 NO ROW APPLIED — and 3 is not
# success: a claim naming profiles the tool has no row for has not been measured.
conform-tool: gen
	@if [ ! -x "$(PPCP_CONFORM)" ]; then \
		echo "make conform: no ppcp-conform at $(PPCP_CONFORM)"; \
		echo "  Build it:  cmake --build --preset dev -j3 --target ppcp-conform ppcp-sim"; \
		echo "  (in $(LIBPPCP))"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make conform: no available iPhone simulator found."; exit 1; \
	fi
	@mkdir -p $(CONFORM_OUT)
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	log=$$(mktemp -t ppcp-conform-log); \
	testlog=$$(mktemp -t ppcp-conform-test); \
	port=$$(python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()'); \
	echo "ppcp-conform on port $$port, profiles $(CONFORM_PROFILES)"; \
	echo "starting the simulator first — see the ordering note above"; \
	TEST_RUNNER_PPCP_CONFORM_TOOL_PORT=$$port xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:PinPointCaptureTests/ConformanceHarnessTests \
		-default-test-execution-time-allowance 600 \
		-maximum-test-execution-time-allowance 900 \
		>"$$testlog" 2>&1 & \
	testpid=$$!; \
	trap 'kill $$testpid $$toolpid 2>/dev/null || true' EXIT; \
	sleep $(CONFORM_WARMUP_S); \
	"$(PPCP_CONFORM)" --profiles $(CONFORM_PROFILES) --role capture \
		--listen $$port --column PinPointCapture \
		--json $(CONFORM_OUT)/ppcp-conform.json \
		--markdown $(CONFORM_OUT)/ppcp-conform.md \
		--sim $(PPCP_SIM) --scenarios $(LIBPPCP)/tools/scenarios \
		>"$$log" 2>&1 & \
	toolpid=$$!; \
	rc=0; wait $$toolpid || rc=$$?; \
	kill $$testpid 2>/dev/null || true; \
	wait $$testpid 2>/dev/null || true; \
	grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' "$$testlog" || true; \
	echo "--- ppcp-conform ---"; cat "$$log"; \
	case $$rc in \
	  0) echo "make conform: every applicable row passed";; \
	  1) echo "make conform: A ROW FAILED — see the table above and $(CONFORM_OUT)/ppcp-conform.md";; \
	  2) echo "make conform: bad invocation";; \
	  3) echo "make conform: NO ROW APPLIED to this claim and role — not a pass";; \
	  *) echo "make conform: ppcp-conform exited $$rc";; \
	esac; \
	exit $$rc

# ─────────────────────────────────────────────────────────────────────────────
# `CONF` §5 wave 1 — the two rows where this device is a real party, in ONE
# simulator launch.
#
#     make conform-iop
#
# ⛔ **Two counterparts, one launch, and that is not thrift.** Booting,
# installing and launching a simulator costs tens of seconds; a row costs twenty.
# So `ppcp-sim` is started twice — IOP-2's foreign, three-clock host on one port
# and IOP-1's reference host on another — and the suite runs once, dialling each
# in turn. Every port is bound by the tool with `--listen 0`, so nothing collides
# with another agent's run.
#
#   IOP-2  three-timebase-host.json + reference-host  — two machine-vision
#          cameras, each on its own clock, both `convention: start` /
#          `geometry: global`. Proves I19 (this device declares what it is) and
#          I22 (an issued `t0` on the host's clock is CONVERTED here, not
#          adopted).
#   IOP-1  reference-host.json + reference-host — the full session, plus a
#          `session_offer` of two stored Sessions and their replay (`MSG` §9.1,
#          `ENC` 7a). `offers_rx=2` is the far end's half of the assertion.
#
# ⛔ **`--run-ms` outlives the test, deliberately.** A counterpart that exits
# first closes the link mid-row and the failure reads as a refusal.
IOP_RUN_MS ?= 200000
# Which tests the run drives. ⚠ **`make conform-iop IOP_TESTS=` runs the WHOLE
# suite**, which is how one simulator launch covers `make test-app` as well as
# the two rows: booting, installing and launching costs tens of seconds and the
# rest of the suite needs no counterpart — every test that does skips without a
# port in the environment.
IOP_TESTS ?= -only-testing:PinPointCaptureTests/ConformanceHarnessTests

conform-iop: gen
	@if [ ! -x "$(PPCP_SIM)" ]; then \
		echo "make conform-iop: no ppcp-sim at $(PPCP_SIM)"; exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make conform-iop: no available iPhone simulator found."; exit 1; \
	fi
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	p2=$$(mktemp -t ppcp-iop2-port); l2=$$(mktemp -t ppcp-iop2-log); \
	p1=$$(mktemp -t ppcp-iop1-port); l1=$$(mktemp -t ppcp-iop1-log); \
	"$(PPCP_SIM)" --role host --listen 0 --port-file "$$p2" --log-prefix iop2 \
		--declaration $(LIBPPCP)/tools/scenarios/three-timebase-host.json \
		--scenario reference-host --expect violations=0 \
		--run-ms $(IOP_RUN_MS) >"$$l2" 2>&1 & \
	sim2=$$!; \
	"$(PPCP_SIM)" --role host --listen 0 --port-file "$$p1" --log-prefix iop1 \
		--declaration $(LIBPPCP)/tools/scenarios/reference-host.json \
		--scenario reference-host --expect violations=0 --expect offers_rx=2 \
		--run-ms $(IOP_RUN_MS) >"$$l1" 2>&1 & \
	sim1=$$!; \
	trap 'kill $$sim1 $$sim2 2>/dev/null || true' EXIT; \
	for i in 1 2 3 4 5 6 7 8 9 10; do \
		[ -s "$$p2" ] && [ -s "$$p1" ] && break; sleep 0.3; \
	done; \
	port2=$$(cat "$$p2" 2>/dev/null); port1=$$(cat "$$p1" 2>/dev/null); \
	if [ -z "$$port2" ] || [ -z "$$port1" ]; then \
		echo "make conform-iop: a ppcp-sim never reported a port"; \
		cat "$$l2" "$$l1"; exit 1; fi; \
	echo "IOP-2 (three-timebase-host) on $$port2, IOP-1 (reference-host) on $$port1"; \
	rc=0; \
	set -o pipefail; \
	TEST_RUNNER_PPCP_IOP2_PORT=$$port2 TEST_RUNNER_PPCP_IOP1_PORT=$$port1 \
	TEST_RUNNER_PPCP_CONFORM_ROW=iop xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		$(IOP_TESTS) \
		-default-test-execution-time-allowance 300 \
		-maximum-test-execution-time-allowance 600 \
		2>&1 | grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' || rc=$$?; \
	echo "--- ppcp-sim, IOP-2 (three-timebase-host) ---"; tail -3 "$$l2"; \
	echo "--- ppcp-sim, IOP-1 (reference-host) ---";      tail -3 "$$l1"; \
	kill $$sim1 $$sim2 2>/dev/null || true; \
	if [ $$rc != 0 ]; then \
		echo "make conform-iop: A ROW FAILED — see the transcript above"; exit $$rc; fi; \
	echo "make conform-iop: both rows passed on the device side"; \
	$(MAKE) --no-print-directory pull-bundles

# IOP-3 / IOP-10, the receiving half — read a bundle another implementation
# wrote, through `SessionBundleReader`.
#
#     make read-bundle FILE=../PinPointStudio/docs/conformance/bundles/x.ppcpbndl
#
# ⚠ Native, no simulator: the reader is `CaptureCore` and `CaptureCore` is
# platform-free by construction (REQ-PORT-3).
read-bundle:
	@if [ -z "$(FILE)" ]; then echo "make read-bundle: FILE=<path.ppcpbndl> is required"; exit 1; fi
	@if [ ! -f "$(FILE)" ]; then echo "make read-bundle: no such file: $(FILE)"; exit 1; fi
	@cd Packages/Core && PPCP_BUNDLE_IN="$(abspath $(FILE))" swift test -j $(JOBS) \
		--filter ImportedBundleTests 2>&1 | grep -E '^(◇|✔|✘|↳)|imported |error:|Test run'

# The bundles an IOP-1 / `make interop` run wrote, copied out of the simulator's
# app container into the repository.
#
# ⚠ **`booted`, and it is the one fragile thing here.** A test writes into the
# app's Documents directory, which lives inside a container only `simctl` can
# name. With two simulators booted this picks the wrong one; the target says what
# it found rather than failing quietly.
pull-bundles:
	@set -e; \
	dir=$$(xcrun simctl get_app_container booted $(BUNDLE_ID) data 2>/dev/null || true); \
	if [ -z "$$dir" ]; then \
		echo "make pull-bundles: no booted simulator holding $(BUNDLE_ID)."; \
		echo "  Run a row first:  make conform ROW=iop1"; exit 1; \
	fi; \
	mkdir -p $(BUNDLE_OUT); \
	found=0; \
	for b in "$$dir/Documents/interop-bundles"*/*/*.ppcpbndl; do \
		[ -e "$$b" ] || continue; \
		: '⚠ NOT `dir` — that is the container path this loop still needs, and'; \
		: 'reusing it here cost a run: the summaries were looked for under a'; \
		: 'bundle directory name and silently not found.'; \
		: '⚠ The directory is `<peer>~<session>` and a `peer:` is a fresh UUID per'; \
		: 'install, so the checked-in name is the SESSION half with the two bytes'; \
		: 'a path cannot carry replaced. 5.1a — nothing is parsed back out of it.'; \
		bdir=$$(basename $$(dirname "$$b")); \
		name=$$(printf '%s' "$${bdir#*~}" | tr ':/' '--'); \
		cp "$$b" "$(BUNDLE_OUT)/$$name.ppcpbndl"; \
		found=$$((found+1)); \
		echo "  $(BUNDLE_OUT)/$$name.ppcpbndl  $$(wc -c <"$$b" | tr -d ' ') bytes"; \
	done; \
	if [ "$$found" = "0" ]; then echo "make pull-bundles: no .ppcpbndl found"; fi; \
	for j in interop-summary.json interop-acoustic-summary.json; do \
		if [ -f "$$dir/Documents/$$j" ]; then \
			cp "$$dir/Documents/$$j" $(CONFORM_OUT)/$$j; echo "  $(CONFORM_OUT)/$$j"; \
		fi; \
	done

# ─────────────────────────────────────────────────────────────────────────────
# WAVE 2 — the real pair. This device, in the simulator, dialling the REAL
# PinPointStudio TLS listener.
#
#     make interop HOST=127.0.0.1:9443 PSK=<64 hex chars> IDENTITY=<hex or text>
#
# ⛔ **No harness transport.** `PPCP_INTEROP_HOST` makes `ConformanceHarness`
# dial `PpcpConnector` — `Network.framework`, `RV` §5's TLS profile, the file
# with no plaintext branch in it — rather than the `DEBUG` plaintext connector
# `ppcp-sim` speaks. `PSK` is the 32-byte `K_tls` a scanned pairing code would
# have derived (`RV` §3); supplying it directly is the *shape* that produces, and
# the derivation itself is D7's own tested path.
#
# ⚠ **PinPointStudio provides the listener**, and it must be running before this
# starts: the device dials and does not retry for long. What the run does, in
# order — a hostless Session recorded and stored (one minted Shot, its Captures
# `absent`/`outside_buffer` because a simulator has no camera), then the dial,
# the `MSG` §3 handshake, the Session, a Stream per declared Source, the `arm`
# answered with a Readiness measurement, one injected swing through the real
# detector to a Candidate, and the stored Session offered and replayed.
#
# The summary is JSON: declares, candidates tx, shots rx, offers tx/accepted,
# errors. It is written inside the app container and copied to
# `$(CONFORM_OUT)/interop-summary.json`.
interop: gen
	@if [ -z "$(HOST)" ] || [ -z "$(PSK)" ]; then \
		echo "make interop: HOST=<host:port> and PSK=<64 hex chars> are required."; \
		echo "  e.g. make interop HOST=127.0.0.1:9443 PSK=$$(python3 -c 'print(\"ab\"*32)') IDENTITY=deadbeef"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make interop: no available iPhone simulator found."; exit 1; \
	fi
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	echo "dialling $(HOST) $(HOST2) over TLS — the listeners must already be up"; \
	set -o pipefail; \
	TEST_RUNNER_PPCP_INTEROP_HOST=$(HOST) \
	TEST_RUNNER_PPCP_INTEROP_HOST_ACOUSTIC=$(HOST2) \
	TEST_RUNNER_PPCP_INTEROP_PSK=$(PSK) \
	TEST_RUNNER_PPCP_INTEROP_IDENTITY=$(IDENTITY) xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:PinPointCaptureTests/InteropTests \
		-default-test-execution-time-allowance 300 \
		-maximum-test-execution-time-allowance 600 \
		| grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' || true
	@$(MAKE) --no-print-directory pull-bundles || true
	@if [ -f $(CONFORM_OUT)/interop-summary.json ]; then \
		for f in $(CONFORM_OUT)/interop-summary.json $(CONFORM_OUT)/interop-acoustic-summary.json; do \
			[ -f "$$f" ] || continue; echo "--- $$f ---"; cat "$$f"; \
		done; \
	else \
		echo "make interop: no summary was written — the run did not reach the harness."; \
		exit 1; \
	fi

device:
	@xcrun devicectl list devices

# Resolve the first connected device, or explain plainly why we cannot continue.
# Set DEVICE=<identifier> to pin a specific one.
deploy: gen
	@set -e; \
	dev="$(DEVICE)"; \
	if [ -z "$$dev" ]; then \
		tmp=$$(mktemp -t ppcp-devices); \
		xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
		dev=$$(python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
c=[x for x in d if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print(c[0]["identifier"] if c else "")' "$$tmp" 2>/dev/null || echo ""); \
		rm -f "$$tmp"; \
	fi; \
	if [ -z "$$dev" ]; then \
		echo ""; \
		echo "make deploy: no connected device."; \
		echo ""; \
		echo "  Plug an iPhone or iPad in over USB, unlock it, and trust this Mac."; \
		echo "  Check what the Mac can see with:  make device"; \
		echo "  Then pin one explicitly if needed: make deploy DEVICE=<identifier>"; \
		echo ""; \
		exit 1; \
	fi; \
	echo "device: $$dev"; \
	$(MAKE) --no-print-directory build-device; \
	if [ ! -d "$(DEVICE_APP)" ]; then \
		echo "make deploy: $(DEVICE_APP) was not produced by the device build."; \
		exit 1; \
	fi; \
	xcrun devicectl device install app --device "$$dev" "$(DEVICE_APP)"; \
	xcrun devicectl device process launch --device "$$dev" --terminate-existing $(BUNDLE_ID)

lint:
	@swiftlint lint --quiet

clean:
	@rm -rf $(DERIVED) $(PROJECT)
	@echo "cleaned"
