# PinPointCapture — build, test and deploy.
#
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored.
# Run `make gen` after pulling, after adding files, or whenever the project
# looks stale. Never edit the project file by hand.

SCHEME      := PinPointCapture
PROJECT     := PinPointCapture.xcodeproj
APP         := PinPointCapture.app
BUNDLE_ID   := org.pinpointstudio.capture
CONFIG      ?= Debug
DERIVED     := build
# ⚠ Resolved at run time, not hardcoded. The installed simulator set changes
# with every Xcode release — an iOS 27 runtime ships iPhone 17s and no 16.
SIM_NAME    ?= $(shell xcrun simctl list devices available 2>/dev/null \
                 | grep -oE 'iPhone [0-9]+( Pro)?' | head -1)
SIM_DEST    ?= generic/platform=iOS Simulator
TEST_DEST   ?= platform=iOS Simulator,name=$(SIM_NAME)
DEV_DEST    ?= generic/platform=iOS
XCB         := xcbeautify --quieter
DEVICE_APP  := $(DERIVED)/Build/Products/$(CONFIG)-iphoneos/$(APP)

# ⚠ **Every build is capped at three jobs, and it is not a preference.** This is
# a 16 GB machine and an unbounded `xcodebuild` alongside a `swift build` took it
# down on 22 August 2026. `-jobs`/`-j` here rather than in each recipe so a new
# target cannot forget.
JOBS        := 3

# `libppcp`'s conformance tools. A sibling checkout during co-development.
LIBPPCP     ?= ../libppcp
PPCP_SIM    ?= $(LIBPPCP)/build/dev/tools/ppcp-sim/ppcp-sim
PPCP_CONFORM ?= $(LIBPPCP)/build/dev/tools/ppcp-conform/ppcp-conform
# ⚠ **Two axes, and keeping them apart is the point of `tools/scenarios`.** What
# the peer IS is a declaration file; what it DOES is a named scenario. "A host
# that never answers a Candidate" is `SCENARIO=silent-host` over the *reference*
# host declaration — deriving the file name from the scenario looked tidy and
# broke the moment the two differed.
SCENARIO    ?= reference-host
DECL        ?= reference-host
SCENARIO_DECL ?= $(LIBPPCP)/tools/scenarios/$(DECL).json
# ⚠ Long enough for a simulator to install and run, and no longer — the target
# `wait`s for ppcp-sim so it can read the exit code its `--expect` produces, so
# this number is also how long `make conform` takes after the test has passed.
# The device side's own deadline is `ConformanceHarness.run(seconds:)`.
CONFORM_RUN_MS ?= 45000

# ⛔ **The claim** (`CONF` 1a): a conformance run without a profile set is not a
# claim. This is the set `docs/ppcp-conformance.md` §1 states, and the two must
# not drift — a row that passes against a set this application does not claim is
# measuring somebody else.
CONFORM_PROFILES ?= core,capture,detect,mint,live,offline,markup
CONFORM_OUT      ?= docs/conformance
# How long the simulator gets to boot, install and reach the dial loop before
# `ppcp-conform` starts binding ports. ⚠ Generous on purpose: a row lost to a
# slow boot is a FAILED row, and there is no way to tell that apart from a real
# refusal afterwards.
CONFORM_WARMUP_S ?= 75

.PHONY: all gen build build-device _udid test test-core test-app conform conform-sim conform-tool device deploy lint clean help

# ⚠ **Two instruments, one target.** `make conform` runs `ppcp-conform`, which is
# what fills the matrix column (plan A11). `make conform SCENARIO=<name>` keeps
# the direct `ppcp-sim` path, which is how a single scenario is driven while
# debugging one. `$(origin ...)` is what tells an explicit SCENARIO from the
# default sitting in this file.
ifeq ($(origin SCENARIO),command line)
conform: conform-sim
else
conform: conform-tool
endif

all: build

help:
	@echo "gen           regenerate $(PROJECT) from project.yml"
	@echo "build         build for the simulator"
	@echo "build-device  build for a physical device (needs signing)"
	@echo "test          run the unit tests"
	@echo "conform       ppcp-conform drives the device (D9); SCENARIO=<n> for one ppcp-sim row"
	@echo "device        list connected devices"
	@echo "deploy        gen + build-device + install + launch on a connected device"
	@echo "lint          run swiftlint"
	@echo "clean         remove generated project and build products"

gen:
	@xcodegen generate --quiet
	@echo "generated $(PROJECT)"

$(PROJECT):
	@$(MAKE) --no-print-directory gen

# ⚠ Depends on `gen`, not on $(PROJECT). project.yml globs Sources/, so adding a
# new file leaves project.yml untouched and a timestamp rule would rebuild a
# stale project that omits it — surfacing as "cannot find X in scope".
# xcodegen takes well under a second; correctness is worth more than that.
build: gen
	set -o pipefail && xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(SIM_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)

# ⚠ Builds against the CONNECTED device by UDID, not against a generic iOS
# destination. Automatic signing has to name a specific device to include it in a
# provisioning profile; with `generic/platform=iOS` it cannot, and fails with the
# misleading "Your team has no devices" rather than naming the phone.
# Override with:  make build-device UDID=<udid>
build-device: gen
	@set -e; \
	udid="$(UDID)"; \
	if [ -z "$$udid" ]; then udid=$$($(MAKE) --no-print-directory _udid); fi; \
	if [ -z "$$udid" ]; then \
		echo "make build-device: no connected device. Try: make device"; exit 1; \
	fi; \
	echo "device UDID: $$udid"; \
	set -o pipefail && xcodebuild build \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination "id=$$udid" \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		-allowProvisioningUpdates \
		| $(XCB)

# Resolve the UDID of the first connected physical device. Prints nothing if none.
_udid:
	@tmp=$$(mktemp -t ppcp-devices); \
	xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
	python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
c=[x for x in d if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print(c[0]["hardwareProperties"]["udid"] if c else "")' "$$tmp" 2>/dev/null || true; \
	rm -f "$$tmp"

# Everything. Core first: it is the fast one, and if the layer seam is broken
# there is no point booting a simulator to find out.
test: test-core test-app

# ⚠ The one to reach for. Runs natively on the host in milliseconds — no
# simulator, no runtime download, no Xcode. Includes the layer purity gate that
# fails the build if Core imports a platform framework (REQ-PORT-3).
test-core:
	@cd Packages/Core && swift test -j $(JOBS)

test-app: gen
	@if ! xcrun simctl list runtimes 2>/dev/null | grep -q 'iOS'; then \
		echo "make test-app: no iOS simulator runtime is installed."; \
		echo "  Run: xcodebuild -downloadPlatform iOS"; \
		echo "  (make test-core needs no simulator and covers the Core layer.)"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make test-app: no available iPhone simulator found."; exit 1; \
	fi
	@echo "simulator: $(SIM_NAME)"
	@# ⚠ `↳` is in the filter because swift-testing prefixes the CONTINUATION
	@# lines of a multi-line assertion message with it. Without it the failure
	@# name survives and the transcript attached to it does not — which is
	@# exactly what was thrown away the one time it was wanted (D9, CT-S4 (6)).
	@# ⚠ NOT piped through `xcbeautify --quieter`, which swallows swift-testing's
	@# output entirely and leaves only XCTest's "Executed 0 tests" summary — so a
	@# passing suite looks like an empty one. Filter to the result lines instead.
	set -o pipefail && xcodebuild test \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		-default-test-execution-time-allowance 120 \
		-maximum-test-execution-time-allowance 300 \
		| grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' || \
		(echo "make test-app: no test output — see the xcresult bundle"; exit 1)

# D9 — the device peer driven by a counterpart this repository did not write.
#
# ⚠ `ppcp-conform` (libppcp L14) is what this will call once it exists; until
# then it drives `ppcp-sim` directly, which is the same transport and the same
# refusals. The target switches on its own when the binary appears.
#
# ⛔ The simulator peer is started BEFORE the test and killed after, whatever
# happens: a listener left bound holds the port and the next run fails for a
# reason that has nothing to do with conformance.
conform-sim: gen
	@if [ ! -x "$(PPCP_SIM)" ]; then \
		echo "make conform: no ppcp-sim at $(PPCP_SIM)"; \
		echo "  Build it:  cmake --build $(LIBPPCP)/build/dev --target ppcp-sim"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make conform: no available iPhone simulator found."; exit 1; \
	fi
	@# ⛔ **Build first, then start the counterpart.** The first version started
	@# ppcp-sim and then ran `xcodebuild test`, which builds — and a compile is
	@# minutes while `--run-ms` is seconds, so the simulator peer had exited before
	@# the device dialled and the failure looked like a refused connection.
	@# `build-for-testing` / `test-without-building` is what makes the window the
	@# test's rather than the compiler's.
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	portfile=$$(mktemp -t ppcp-conform-port); \
	log=$$(mktemp -t ppcp-conform-log); \
	"$(PPCP_SIM)" --role host --listen 0 --port-file "$$portfile" \
		--declaration "$(SCENARIO_DECL)" --scenario $(SCENARIO) \
		--expect violations=0 --run-ms $(CONFORM_RUN_MS) >"$$log" 2>&1 & \
	simpid=$$!; \
	trap 'kill $$simpid 2>/dev/null || true' EXIT; \
	for i in 1 2 3 4 5 6 7 8 9 10; do \
		[ -s "$$portfile" ] && break; sleep 0.2; \
	done; \
	port=$$(cat "$$portfile" 2>/dev/null); \
	if [ -z "$$port" ]; then echo "make conform: ppcp-sim never reported a port"; \
		cat "$$log"; exit 1; fi; \
	echo "ppcp-sim listening on $$port, scenario $(SCENARIO)"; \
	set -o pipefail; \
	TEST_RUNNER_PPCP_CONFORM_PORT=$$port \
	TEST_RUNNER_PPCP_CONFORM_SCENARIO=$(SCENARIO) xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:PinPointCaptureTests/ConformanceHarnessTests \
		-default-test-execution-time-allowance 120 \
		-maximum-test-execution-time-allowance 300 \
		| grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' \
		|| { echo "--- ppcp-sim ---"; cat "$$log"; exit 1; }; \
	wait $$simpid || { echo "--- ppcp-sim ---"; cat "$$log"; \
		echo "make conform: ppcp-sim exited non-zero — a violation or an unmet expectation"; \
		exit 1; }; \
	echo "--- ppcp-sim ---"; cat "$$log"

# D9's claim — `ppcp-conform` drives this device through every applicable row of
# `PPCP-CONF` §3 and §4 and emits the matrix fragment.
#
# ⚠ **`--listen`, not `--connect`.** The device DIALS: `PpcpDirectConnector` is a
# connector and there is no plaintext listener anywhere in the app, which is also
# how `RV` 2c1's "nothing to accept on" stays easy to hold. The tool spawns one
# `ppcp-sim` per row, sequentially, on that one port — so the device dials once
# per row, which is what `ConformanceHarnessTests.ppcpConformDrivesTheDevice()`
# does.
#
# ⛔ **THE SIMULATOR STARTS FIRST, AND THEN THE TOOL.** `ppcp-conform` gives each
# row 5–8 s and moves on; a simulator takes tens of seconds to boot, install and
# launch. Starting the tool first burned every row waiting for a device that was
# still starting up — all four failed "timed out waiting for two bound channels",
# which is the same mistake as starting the counterpart before the build, one
# layer further in. So the test is launched, `CONFORM_WARMUP_S` is allowed for it
# to reach its dial loop, and only then does the tool begin binding ports.
#
# ⛔ **The verdict is the tool's exit code, not the test's.** 0 every applicable
# row passed, 1 a row failed, 2 a bad invocation, 3 NO ROW APPLIED — and 3 is not
# success: a claim naming profiles the tool has no row for has not been measured.
conform-tool: gen
	@if [ ! -x "$(PPCP_CONFORM)" ]; then \
		echo "make conform: no ppcp-conform at $(PPCP_CONFORM)"; \
		echo "  Build it:  cmake --build --preset dev -j3 --target ppcp-conform ppcp-sim"; \
		echo "  (in $(LIBPPCP))"; \
		exit 1; \
	fi
	@if [ -z "$(SIM_NAME)" ]; then \
		echo "make conform: no available iPhone simulator found."; exit 1; \
	fi
	@mkdir -p $(CONFORM_OUT)
	set -o pipefail && xcodebuild build-for-testing \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-jobs $(JOBS) \
		| $(XCB)
	@set -e; \
	log=$$(mktemp -t ppcp-conform-log); \
	testlog=$$(mktemp -t ppcp-conform-test); \
	port=$$(python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()'); \
	echo "ppcp-conform on port $$port, profiles $(CONFORM_PROFILES)"; \
	echo "starting the simulator first — see the ordering note above"; \
	TEST_RUNNER_PPCP_CONFORM_TOOL_PORT=$$port xcodebuild test-without-building \
		-project $(PROJECT) \
		-scheme $(SCHEME) \
		-configuration $(CONFIG) \
		-destination '$(TEST_DEST)' \
		-derivedDataPath $(DERIVED) \
		-only-testing:PinPointCaptureTests/ConformanceHarnessTests \
		-default-test-execution-time-allowance 600 \
		-maximum-test-execution-time-allowance 900 \
		>"$$testlog" 2>&1 & \
	testpid=$$!; \
	trap 'kill $$testpid $$toolpid 2>/dev/null || true' EXIT; \
	sleep $(CONFORM_WARMUP_S); \
	"$(PPCP_CONFORM)" --profiles $(CONFORM_PROFILES) --role capture \
		--listen $$port --column PinPointCapture \
		--json $(CONFORM_OUT)/ppcp-conform.json \
		--markdown $(CONFORM_OUT)/ppcp-conform.md \
		--sim $(PPCP_SIM) --scenarios $(LIBPPCP)/tools/scenarios \
		>"$$log" 2>&1 & \
	toolpid=$$!; \
	rc=0; wait $$toolpid || rc=$$?; \
	kill $$testpid 2>/dev/null || true; \
	wait $$testpid 2>/dev/null || true; \
	grep -E '^(◇|✔|✘|↳)|error:|Test run|\*\* TEST' "$$testlog" || true; \
	echo "--- ppcp-conform ---"; cat "$$log"; \
	case $$rc in \
	  0) echo "make conform: every applicable row passed";; \
	  1) echo "make conform: A ROW FAILED — see the table above and $(CONFORM_OUT)/ppcp-conform.md";; \
	  2) echo "make conform: bad invocation";; \
	  3) echo "make conform: NO ROW APPLIED to this claim and role — not a pass";; \
	  *) echo "make conform: ppcp-conform exited $$rc";; \
	esac; \
	exit $$rc

device:
	@xcrun devicectl list devices

# Resolve the first connected device, or explain plainly why we cannot continue.
# Set DEVICE=<identifier> to pin a specific one.
deploy: gen
	@set -e; \
	dev="$(DEVICE)"; \
	if [ -z "$$dev" ]; then \
		tmp=$$(mktemp -t ppcp-devices); \
		xcrun devicectl list devices --json-output "$$tmp" >/dev/null 2>&1 || true; \
		dev=$$(python3 -c 'import json,sys;\
d=json.load(open(sys.argv[1])).get("result",{}).get("devices",[]);\
c=[x for x in d if x.get("connectionProperties",{}).get("tunnelState")=="connected"];\
print(c[0]["identifier"] if c else "")' "$$tmp" 2>/dev/null || echo ""); \
		rm -f "$$tmp"; \
	fi; \
	if [ -z "$$dev" ]; then \
		echo ""; \
		echo "make deploy: no connected device."; \
		echo ""; \
		echo "  Plug an iPhone or iPad in over USB, unlock it, and trust this Mac."; \
		echo "  Check what the Mac can see with:  make device"; \
		echo "  Then pin one explicitly if needed: make deploy DEVICE=<identifier>"; \
		echo ""; \
		exit 1; \
	fi; \
	echo "device: $$dev"; \
	$(MAKE) --no-print-directory build-device; \
	if [ ! -d "$(DEVICE_APP)" ]; then \
		echo "make deploy: $(DEVICE_APP) was not produced by the device build."; \
		exit 1; \
	fi; \
	xcrun devicectl device install app --device "$$dev" "$(DEVICE_APP)"; \
	xcrun devicectl device process launch --device "$$dev" --terminate-existing $(BUNDLE_ID)

lint:
	@swiftlint lint --quiet

clean:
	@rm -rf $(DERIVED) $(PROJECT)
	@echo "cleaned"
