//  HostlessRecordingSession.swift
//  The composition D3 left open: a `DevicePeer`, a `SessionBundleWriter` and a
//  `CaptureSessionRecorder`, wired to a file and to the real capture stack.
//
//  ⚠ **Nothing in `Sources/` composed these until D4.** D2 built the declaration
//  and D3 built the bundle, and both were exercised only from their own test
//  suites — which is a working library and not a working application. This is the
//  first place the two meet a real device and a real file.
//
//  ⛔ **This is the hostless path** (`CORE` 4.1b, 7.3b): the peer opens its own
//  Session with **no arbitration parameters**, records no `arm` and no `disarm`,
//  and records `readiness` because 7.3c confers that through **Capture** rather
//  than through Live. None of those rules is remembered here — `ppcp_session_make_
//  hostless` cannot be given the parameters, `ppcp_peer_arm` refuses a peer that
//  is not `role: host`, and the writer refuses an `arm` after a hostless
//  `session_open`.
//
//  ⚠ **Bytes go through a file handle and nowhere else.** `CaptureCore` opens no
//  file (ground rule 8); the writer hands back every byte in order and this is
//  the embedding that appends them.
//
//  Spec: `CORE` §5.2.1, §7.3, §9; `ENC` §7; `CONF` CT-S4 (1).

import Foundation
import CaptureCore

// MARK: - Peer identity

/// `CORE` 5.2.1a — "generated by the peer and persisted in its own store".
///
/// ⛔ 5.2.1b: **never** a platform device identifier and never an advertising
/// identifier. A random UUID generated once and kept is the whole requirement;
/// `identifierForVendor` would be shorter to write and is exactly what the clause
/// forbids, because it is stable across applications and outside this peer's
/// control.
public enum PeerIdentity {

    private static let key = "org.pinpointstudio.capture.ppcp.peerId"

    /// This peer's id, minted on first use and stable thereafter.
    public static var current: String {
        let defaults = UserDefaults.standard
        if let existing = defaults.string(forKey: key), existing.isEmpty == false {
            return existing
        }
        let minted = "peer:\(UUID().uuidString.lowercased())"
        defaults.set(minted, forKey: key)
        return minted
    }
}

// MARK: - The session

/// One recording session, written to a bundle as it happens.
@MainActor
public final class HostlessRecordingSession {

    public let bundle: SessionBundle
    public let sessionId: String
    public let peerId: String

    private let handle: FileHandle
    private let recorder: CaptureSessionRecorder
    private var isClosed = false

    /// - Parameters:
    ///   - device: asked for its declaration. ⛔ Through the port, so the
    ///     declaration comes from the capability the hardware actually enumerated
    ///     (REQ-FPS-1) and never from a spec sheet.
    ///   - videoProfileId: which declared `CaptureProfile` the video Stream
    ///     activates. `nil` takes the first the camera Source offers.
    public init(store: SessionStore,
                device: any CaptureDevice,
                sessionId: String,
                peerId: String = PeerIdentity.current,
                videoProfileId: String? = nil) throws {
        self.sessionId = sessionId
        self.peerId = peerId
        self.bundle = try store.makeBundle(sessionId: sessionId, mintingPeerId: peerId)

        let file = bundle.bundleFile
        FileManager.default.createFile(atPath: file.path, contents: nil)
        handle = try FileHandle(forWritingTo: file)

        let peer = try DevicePeer(peerId: peerId)
        // ⚠ `emit` is called with each run of bytes in order and never with a
        // whole bundle: `ENC` §7 is a stream, and buffering it would make an
        // interrupted session an empty file rather than a `partial` one (7d).
        let writer = try SessionBundleWriter(peer: peer) { [handle] bytes in
            try handle.write(contentsOf: bytes)
        }
        let declaration = try PpcpDeclaration(
            device.ppcpDeclarationInput(peerId: peerId, viewpoint: nil))

        recorder = try CaptureSessionRecorder(
            writer: writer,
            declaration: declaration,
            // ⛔ `PpcpSessionRecord` has no arbitration parameters to give, and
            // `epoch` is a LABEL (I15) — a wall instant paired with the capture
            // instant it was read beside, never used to compute an interval.
            session: PpcpSessionRecord(
                id: sessionId,
                timebaseRef: PpcpTimebases.captureId,
                epochWallUtcNs: Int64(Date().timeIntervalSince1970 * 1_000_000_000),
                epochAtNs: MachClock.hostTimeNs,
                epochTimebaseId: PpcpTimebases.captureId))

        // ⛔ The Streams are derived from the declaration, not passed in. A
        // Stream's `source_id`, `profile_id` and `timebase_id` must name things
        // the peer actually declared (5.11a, I5), and a caller assembling them by
        // hand is a caller who can name one that does not exist.
        streams = Self.streams(sessionId: sessionId, declaration: declaration,
                               videoProfileId: videoProfileId,
                               openedAtNs: MachClock.hostTimeNs)
        for stream in streams { try recorder.open(stream: stream) }
    }

    /// The Streams a hostless capture session opens, from what was declared.
    ///
    /// ⚠ §5.11's continuity table is normative and is followed rather than
    /// chosen: `video` is always `shot_windowed`, `metadata` always `continuous`.
    nonisolated static func streams(sessionId: String,
                                    declaration: PpcpDeclaration,
                                    videoProfileId: String?,
                                    openedAtNs: Int64) -> [PpcpStreamRecord] {
        var built: [PpcpStreamRecord] = []

        if let camera = declaration.sources.first(where: { $0.kind == "camera" }),
           let profile = videoProfileId ?? camera.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:video:\(camera.id)", sessionId: sessionId,
                sourceId: camera.id, kind: PpcpStreamKind.video,
                profileId: profile, timebaseId: camera.timebaseId,
                continuity: .shotWindowed, openedAtNs: openedAtNs))
        }
        if let imu = declaration.sources.first(where: { $0.kind == "imu" }),
           let profile = imu.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:metadata:\(imu.id)", sessionId: sessionId,
                sourceId: imu.id, kind: PpcpStreamKind.metadata,
                profileId: profile, timebaseId: imu.timebaseId,
                continuity: .continuous, openedAtNs: openedAtNs))
        }
        return built
    }

    /// The Streams this session opened, in the order they were opened.
    public private(set) var streams: [PpcpStreamRecord] = []

    /// The `video` Stream, for a Capture to land on.
    public var videoStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.video }
    }

    /// The `continuous` `metadata` Stream, if the device declared an IMU.
    public var metadataStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.metadata }
    }

    /// `CORE` 7.3c — in response to `arm` where one was sent, and in any case
    /// whenever `settled` changes.
    public func report(_ readiness: ReadinessMeasurement, streamIds: [String] = []) throws {
        try recorder.report(readiness, streamIds: streamIds)
    }

    /// `CORE` 7.3d.
    public func record(_ interruption: InterruptionRecord) throws {
        try recorder.record(interruption)
    }

    /// One shot-anchored Capture and the bytes behind it.
    public func announce(_ assembly: CaptureAssembly, clip: Data?) throws {
        // ⚠ The clip is written to its own file under `clips/` and read back when
        // the payload frames go out after the manifest (`ENC` 7c). Holding a
        // session's clips in memory to satisfy a frame-ordering rule would be
        // hundreds of megabytes for nothing.
        guard let clip else {
            try recorder.announce(assembly)
            return
        }
        let url = bundle.clipsDirectory.appendingPathComponent("\(assembly.record.id).mp4")
        try FileManager.default.createDirectory(at: bundle.clipsDirectory,
                                                withIntermediateDirectories: true)
        try clip.write(to: url, options: .atomic)
        try recorder.announce(assembly, clip: { try Data(contentsOf: url) })
    }

    /// The next segment of a `continuous` Stream.
    public func announceSegment(_ record: PpcpCaptureRecord,
                                coverage: StreamCoverage) throws {
        try recorder.announceSegment(record, coverage: coverage)
    }

    public func coverage(of streamId: String) -> StreamCoverage? {
        recorder.coverage(of: streamId)
    }

    public func countShot() { recorder.countShot() }

    /// `MSG` §9.2 then `ENC` §6, then the finish that emits no bytes (7e).
    ///
    /// - Parameter completeness: ⛔ **asserted**, never inferred (I10). A session
    ///   the application abandoned says `partial` and means it, and a `complete`
    ///   one is refused outright where a `continuous` Stream has unaccounted time
    ///   (I36, CT-I36 (d)).
    public func close(completeness: PpcpCaptureRecord.Completeness = .partial,
                      closedAtNs: Int64? = nil) throws {
        guard isClosed == false else { return }
        isClosed = true
        try recorder.close(completeness: completeness, closedAtNs: closedAtNs)
        try handle.close()
    }
}
