//  HostlessRecordingSession.swift
//  The composition D3 left open: a `DevicePeer`, a `SessionBundleWriter` and a
//  `CaptureSessionRecorder`, wired to a file and to the real capture stack.
//
//  ⚠ **Nothing in `Sources/` composed these until D4.** D2 built the declaration
//  and D3 built the bundle, and both were exercised only from their own test
//  suites — which is a working library and not a working application. This is the
//  first place the two meet a real device and a real file.
//
//  ⛔ **This is the hostless path** (`CORE` 4.1b, 7.3b): the peer opens its own
//  Session with **no arbitration parameters**, records no `arm` and no `disarm`,
//  and records `readiness` because 7.3c confers that through **Capture** rather
//  than through Live. None of those rules is remembered here — `ppcp_session_make_
//  hostless` cannot be given the parameters, `ppcp_peer_arm` refuses a peer that
//  is not `role: host`, and the writer refuses an `arm` after a hostless
//  `session_open`.
//
//  ⚠ **Bytes go through a file handle and nowhere else.** `CaptureCore` opens no
//  file (ground rule 8); the writer hands back every byte in order and this is
//  the embedding that appends them.
//
//  Spec: `CORE` §5.2.1, §7.3, §9; `ENC` §7; `CONF` CT-S4 (1).

import Foundation
import CaptureCore

// MARK: - Peer identity

/// `CORE` 5.2.1a — "generated by the peer and persisted in its own store".
///
/// ⛔ 5.2.1b: **never** a platform device identifier and never an advertising
/// identifier. A random UUID generated once and kept is the whole requirement;
/// `identifierForVendor` would be shorter to write and is exactly what the clause
/// forbids, because it is stable across applications and outside this peer's
/// control.
public enum PeerIdentity {

    private static let key = "org.pinpointstudio.capture.ppcp.peerId"

    /// This peer's id, minted on first use and stable thereafter.
    public static var current: String {
        let defaults = UserDefaults.standard
        if let existing = defaults.string(forKey: key), existing.isEmpty == false {
            return existing
        }
        let minted = "peer:\(UUID().uuidString.lowercased())"
        defaults.set(minted, forKey: key)
        return minted
    }
}

// MARK: - The session

/// One recording session, written to a bundle as it happens.
@MainActor
public final class HostlessRecordingSession {

    public let bundle: SessionBundle
    public let sessionId: String
    public let peerId: String

    private let handle: FileHandle
    private let recorder: CaptureSessionRecorder
    private var isClosed = false

    /// D5's pipeline, composed here rather than in a test for the first time.
    /// ⛔ `nil` only where the device declared no microphone — a Session with no
    /// nominator is a legitimate record and not a failure.
    public private(set) var detect: DetectAndMint?
    /// The declaration this Session was opened with, kept because
    /// `CandidateFactory` and the Streams both name things inside it.
    public let declaration: PpcpDeclaration
    /// 8.1d — what every Candidate's raw instant is corrected by.
    public let micToBall: MicToBallDistance

    /// A4's audio retention setting, as the policy the detector enforces.
    ///
    /// ⛔ **It was inert.** `AppModel.audioRetention` has existed since the first
    /// build and never reached `DetectAndMint.Configuration.retention`, so the
    /// user-visible control on the permissions screen changed a label and nothing
    /// else — the exact shape of dishonesty REQ-PRIV-2 forbids, since the setting
    /// is what the privacy label describes.
    public let retention: CandidateAudioRetention

    /// The one wall-clock↔monotonic correspondence this Session carries.
    ///
    /// ⚠ Built from the **same** two readings the `PpcpSessionRecord` epoch
    /// already carries (I15), rather than taken again — two anchors a few
    /// microseconds apart would let a shot be labelled differently depending on
    /// which one a caller reached for.
    public private(set) var anchor: WallClockAnchor = WallClockAnchor(hostTimeNs: 0,
                                                                     wallClock: .distantPast)

    /// - Parameters:
    ///   - device: asked for its declaration. ⛔ Through the port, so the
    ///     declaration comes from the capability the hardware actually enumerated
    ///     (REQ-FPS-1) and never from a spec sheet.
    ///   - mode: which camera and which declared `CaptureProfile` the video
    ///     Stream activates. ⛔ **The mode, not a profile id string** (#102):
    ///     the id a caller would have spelled and the id the declaration emits
    ///     were different, so the Stream named a profile that did not exist
    ///     (5.11a, I5). `nil` takes the first profile the first camera Source
    ///     offers, which is only right when the device has one camera.
    ///   - micToBall: 8.1d — the microphone-to-ball distance and its dispersion.
    ///     ⛔ It reaches every Candidate through `CandidateFactory`; before S4
    ///     nothing supplied one and every device Candidate went out with no
    ///     `tof_correction` at all.
    public init(store: SessionStore,
                device: any CaptureDevice,
                sessionId: String,
                peerId: String = PeerIdentity.current,
                mode: VideoMode? = nil,
                micToBall: MicToBallDistance = MicToBallDistanceStore.load(),
                retention: CandidateAudioRetention = CandidateAudioRetention()) throws {
        self.micToBall = micToBall
        self.retention = retention
        self.sessionId = sessionId
        self.peerId = peerId
        self.bundle = try store.makeBundle(sessionId: sessionId, mintingPeerId: peerId)

        let file = bundle.bundleFile
        FileManager.default.createFile(atPath: file.path, contents: nil)
        handle = try FileHandle(forWritingTo: file)

        // ⛔ Read adjacently and used twice. `epoch` is a LABEL (I15): the wall
        // reading names the moment, the host-time reading measures from it.
        let epochWall = Date()
        let epochAtNs = MachClock.hostTimeNs

        let peer = try DevicePeer(peerId: peerId)
        // ⚠ `emit` is called with each run of bytes in order and never with a
        // whole bundle: `ENC` §7 is a stream, and buffering it would make an
        // interrupted session an empty file rather than a `partial` one (7d).
        let writer = try SessionBundleWriter(peer: peer) { [handle] bytes in
            try handle.write(contentsOf: bytes)
        }
        let declaration = try PpcpDeclaration(
            device.ppcpDeclarationInput(peerId: peerId, viewpoint: nil))
        self.declaration = declaration

        recorder = try CaptureSessionRecorder(
            writer: writer,
            declaration: declaration,
            // ⛔ `PpcpSessionRecord` has no arbitration parameters to give, and
            // `epoch` is a LABEL (I15) — a wall instant paired with the capture
            // instant it was read beside, never used to compute an interval.
            session: PpcpSessionRecord(
                id: sessionId,
                timebaseRef: PpcpTimebases.captureId,
                epochWallUtcNs: Int64(epochWall.timeIntervalSince1970 * 1_000_000_000),
                epochAtNs: epochAtNs,
                epochTimebaseId: PpcpTimebases.captureId))
        // REQ-OFF-8 — the label side of the same epoch, and the only route from a
        // monotonic instant to a date this application shows anyone.
        anchor = WallClockAnchor(hostTimeNs: epochAtNs, wallClock: epochWall)

        // ⛔ The Streams are derived from the declaration, not passed in. A
        // Stream's `source_id`, `profile_id` and `timebase_id` must name things
        // the peer actually declared (5.11a, I5), and a caller assembling them by
        // hand is a caller who can name one that does not exist.
        streams = Self.streams(sessionId: sessionId, declaration: declaration,
                               mode: mode,
                               openedAtNs: MachClock.hostTimeNs)
        for stream in streams { try recorder.open(stream: stream) }

        // ⚠ **The composition D5 wrote and nothing performed.** `DetectAndMint`
        // existed with a full test suite and no caller: the application recorded
        // Streams and a `readiness` and never a Candidate. This is where the
        // detector, the Mint engine, the time-of-flight correction and the ring
        // meet, and it is the whole of D-compose's device half.
        if let audio = streams.first(where: { $0.kind == PpcpStreamKind.audio }),
           let video = streams.first(where: { $0.kind == PpcpStreamKind.video }) ?? streams
               .first(where: { $0.kind == PpcpStreamKind.audio }) {
            let factory = CandidateFactory(
                declaration: declaration,
                sourceId: audio.sourceId,
                // 6.1d — no `format`, therefore no profile and no canonical
                // conversion to apply.
                profileId: nil,
                timeOfFlight: micToBall.timeOfFlight)
            let mint = try DeviceMint(peer: peer,
                                      promotion: DetectAndMint.defaultPromotion())
            detect = DetectAndMint(
                peer: peer, sink: recorder, mint: mint, factory: factory,
                configuration: DetectAndMint.Configuration(
                    sessionId: sessionId, peerId: peerId,
                    // 5.13c — in a hostless Session `timebase_ref` is this
                    // device's own capture timebase, so the conversion is the
                    // identity (I4) and **no relation is asserted for it**.
                    timebaseRefId: PpcpTimebases.captureId,
                    audioStream: audio, videoStream: video,
                    retention: retention),
                promotion: DetectAndMint.defaultPromotion(),
                // ⛔ Through the port, so the answer is the capture stack's and
                // not this file's. A ring that is not retaining answers
                // `outside_buffer`, which 8.4b makes a result rather than a
                // failure (I10).
                extractAudio: { [device] requested in device.extractClip(requested) },
                // ⛔ **The whole of E1.2 and E1.3 is this line changing.** It
                // used to be three closures: an extraction, a hardcoded
                // `.lockedConstant(0)` exposure, and no payload provider at all
                // — so every Shot this application ever minted announced a
                // Capture with a fabricated exposure and no bytes behind it.
                // The device now answers with what it actually retained:
                // measured exposure (5.8d), the intrinsics the connection
                // delivered (REQ-OPT-7), a thermal timeline over the interval,
                // and a lazy provider for the clip.
                videoClip: { [device, bundle] requested in
                    let half = (requested.upperBound - requested.lowerBound) / 2
                    var clip = device.retainedClip(
                        aroundNs: requested.lowerBound + half,
                        preNs: half, postNs: half)
                    Self.persist(&clip, forT0Ns: requested.lowerBound + half,
                                 in: bundle)
                    return clip
                })
        }
    }

    // MARK: Detect (CORE §5.12, §8.2i–j, §8.3)

    /// One window of microphone audio, all the way to nomination.
    ///
    /// ⛔ **Every onset is emitted** (5.12c, 8.3b, I8), including the ones this
    /// peer does not believe. The promotion decision is the Mint engine's and
    /// happens in `pumpMint`.
    @discardableResult
    public func observe(_ window: AudioWindow) throws -> [DetectAndMint.Detection] {
        guard let detect else { return [] }
        let detections = try detect.observe(window)
        for _ in detections { recorder.countCandidate() }
        return detections
    }

    /// 8.2i–j / 8.3a — mint what is due, extract a clip for each Shot.
    @discardableResult
    public func pumpMint(nowRefNs: Int64) throws -> [PpcpShot] {
        guard let detect else { return [] }
        let minted = try detect.pump(nowRefNs: nowRefNs)
        for shot in minted {
            recorder.countShot()
            // E1.2's thumbnail. ⚠ Only reachable here: the clip is written under
            // a `t0` key inside `videoClip`, because `pump` mints the Capture id
            // *after* asking for the clip — so the two are joined up once the
            // Shot comes back carrying it.
            adoptClip(forT0Ns: shot.t0Ns, captureId: shot.captureIds.first)
        }
        return minted
    }

    // MARK: The clip on disk (E1.2)

    /// Where t₀ sits inside an extracted clip. ⚠ Mirrors
    /// `DetectAndMint.Configuration`'s default pre-roll, which is what `pump`
    /// asks the ring for.
    nonisolated static let clipPreNs: Int64 = 1_500_000_000

    /// ⛔ **Materialise the clip NOW, and this is not an optimisation choice.**
    ///
    /// `RetainedClip.payload` reads the ring, and the ring is a **ten-second
    /// rolling buffer**. The bundle writes payloads at `close()` (`ENC` 7c holds
    /// them until after the manifest), by which time the fragments behind a shot
    /// from earlier in the session have long been evicted and the provider would
    /// answer nothing. So the bytes are taken while they still exist and written
    /// to `clips/`, and the provider handed onward reads that file.
    ///
    /// ⚠ The laziness that matters is preserved — a session's clips are ~1.4 GB
    /// and none of them is held in memory. What changes is *where* the provider
    /// reads from: a file rather than a buffer that will not be there.
    nonisolated private static func persist(_ clip: inout RetainedClip,
                                            forT0Ns t0Ns: Int64,
                                            in bundle: SessionBundle) {
        guard let payload = clip.payload else { return }
        do {
            let bytes = try payload()
            try FileManager.default.createDirectory(at: bundle.clipsDirectory,
                                                    withIntermediateDirectories: true)
            let url = Self.pendingClipURL(forT0Ns: t0Ns, in: bundle)
            try bytes.write(to: url, options: .atomic)
            clip.payload = { try Data(contentsOf: url) }
        } catch {
            // ⛔ A clip whose bytes could not be kept is a Capture with no
            // payload, not a Capture with a payload nobody can read. Dropping
            // the provider is what makes the announce honest.
            clip.payload = nil
        }
    }

    /// Keyed on `t0` because the Capture id does not exist yet when the clip is
    /// extracted — `DetectAndMint.pump` mints it afterwards.
    nonisolated private static func pendingClipURL(forT0Ns t0Ns: Int64,
                                                   in bundle: SessionBundle) -> URL {
        bundle.clipsDirectory.appendingPathComponent("t0-\(t0Ns).mp4")
    }

    /// Join the `t0`-keyed clip to the Capture that now names it, and render its
    /// thumbnail.
    ///
    /// ⚠ Thumbnail generation is detached: it decodes a frame, and `pumpMint`
    /// runs on the main actor. A picture for a row is never worth a stutter in
    /// the capture UI.
    private func adoptClip(forT0Ns t0Ns: Int64, captureId: String?) {
        guard let captureId else { return }
        let clipURL = Self.pendingClipURL(forT0Ns: t0Ns, in: bundle)
        guard FileManager.default.fileExists(atPath: clipURL.path) else { return }

        let thumbnailURL = bundle.thumbnailFile(captureId: captureId)
        let directory = bundle.thumbnailsDirectory
        // ⚠ Where t₀ falls inside the clip, not where it falls on the capture
        // clock — the generator only knows about the asset's own timeline.
        let offsetNs = Self.clipPreNs
        Task.detached(priority: .utility) {
            guard let jpeg = try? await ClipThumbnail.jpeg(fromClipAt: clipURL,
                                                           atNs: offsetNs) else { return }
            try? FileManager.default.createDirectory(at: directory,
                                                     withIntermediateDirectories: true)
            try? jpeg.write(to: thumbnailURL, options: .atomic)
        }
    }

    /// The Streams a hostless capture session opens, from what was declared.
    ///
    /// ⚠ §5.11's continuity table is normative and is followed rather than
    /// chosen: `video` is always `shot_windowed`, `metadata` always `continuous`.
    nonisolated static func streams(sessionId: String,
                                    declaration: PpcpDeclaration,
                                    mode: VideoMode?,
                                    openedAtNs: Int64) -> [PpcpStreamRecord] {
        var built: [PpcpStreamRecord] = []

        // ⛔ **The camera the MODE is on, not `sources.first`** (#102). 5.6d
        // declares one Source per physical lens, so with a wide and an
        // ultra-wide both declared, `first` opens an ultra-wide capture's Stream
        // on the wide Source — a Capture attributed to the wrong lens, with the
        // wrong calibration, and nothing in the bundle to show for it.
        //
        // ⚠ Both halves fall back only where there is nothing to be precise
        // about: no mode given, or a mode whose Source or profile the
        // declaration does not carry. A profile id that names nothing is exactly
        // what 5.11a / I5 forbid, so the fallback is the Source's own first
        // profile rather than the caller's string.
        let camera = mode.flatMap { m in
            declaration.sources.first { $0.kind == "camera" && $0.id == m.sourceId }
        } ?? declaration.sources.first { $0.kind == "camera" }

        if let camera,
           let profile = mode.map(\.profileId).flatMap({ id in
               camera.profileIds.contains(id) ? id : nil
           }) ?? camera.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:video:\(camera.id)", sessionId: sessionId,
                sourceId: camera.id, kind: PpcpStreamKind.video,
                profileId: profile, timebaseId: camera.timebaseId,
                continuity: .shotWindowed, openedAtNs: openedAtNs))
        }
        // ⛔ **A separate `audio` Stream, and it was missing.** 5.12.1a puts the
        // window that explains why detection fired on its own Stream, and D5's
        // `DetectAndMint` requires one — but this composition opened only video
        // and metadata, so nothing in the application could nominate. Muxing it
        // into the video clip is the alternative 5.12.1a rules out: it would
        // retain the full video window of room audio per shot for no diagnostic
        // benefit, a privacy cost taken by accident.
        if let microphone = declaration.sources.first(where: { $0.kind == "microphone" }) {
            built.append(PpcpStreamRecord(
                id: "str:audio:\(microphone.id)", sessionId: sessionId,
                sourceId: microphone.id, kind: PpcpStreamKind.audio,
                // ⚠ 6.1d — a microphone declares no `format`, so it has no
                // `CaptureProfile` to activate and the Stream names the Source's
                // own id in its place. `PpcpStreamRecord.profileId` is not
                // optional in the library, and this is the honest filler: a
                // profile id that names nothing would be worse.
                profileId: microphone.profileIds.first ?? microphone.id,
                timebaseId: microphone.timebaseId,
                continuity: .shotWindowed, openedAtNs: openedAtNs))
        }
        if let imu = declaration.sources.first(where: { $0.kind == "imu" }),
           let profile = imu.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:metadata:\(imu.id)", sessionId: sessionId,
                sourceId: imu.id, kind: PpcpStreamKind.metadata,
                profileId: profile, timebaseId: imu.timebaseId,
                continuity: .continuous, openedAtNs: openedAtNs))
        }
        return built
    }

    /// The Streams this session opened, in the order they were opened.
    public private(set) var streams: [PpcpStreamRecord] = []

    /// The `video` Stream, for a Capture to land on.
    public var videoStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.video }
    }

    /// D4's attitude and gravity, on the `continuous` `metadata` Stream.
    ///
    /// ⛔ **Written since D4 and never started until E1.3.** REQ-CLIP-1 lists
    /// "device attitude and gravity" and REQ-META-1 requires the Stream; the
    /// source, its encoder and its segment builder were all complete and
    /// nothing had ever called `start()`, so the Stream was opened and then
    /// carried nothing.
    private let motion = MotionMetadataSource(timebaseId: PpcpTimebases.captureId)
    /// Where the metadata Stream's coverage has reached.
    private var metadataSegmentIndex = 0

    /// Begin sampling attitude and gravity. ⚠ Only where the Stream was actually
    /// opened — the declaration decides whether this device has an IMU, and a
    /// source sampling into no Stream is motion nobody can account for.
    public func startMetadata() {
        guard metadataStream != nil else { return }
        motion.start()
    }

    public func stopMetadata() { motion.stop() }

    /// The next `metadata` segment, if one is due.
    ///
    /// ⛔ **A `continuous` Stream must account for its whole open interval**
    /// (I36), and `close(completeness: .complete)` already refuses a Session
    /// with an unaccounted tail. So this is called on a ticker rather than when
    /// samples happen to be ready — and `segment` produces an `absent` segment
    /// where nothing was sampled, because 5.11c2 makes a named span carrying
    /// nothing an assertion and silence merely a gap in the record.
    @discardableResult
    public func pumpMetadata(nowNs: Int64) throws -> PpcpCaptureRecord? {
        guard let stream = metadataStream,
              var account = recorder.coverage(of: stream.id) else { return nil }
        let due = account.accountedThroughNs
            + Int64(MotionMetadataSource.segmentSeconds * 1_000_000_000)
        guard nowNs >= due else { return nil }

        metadataSegmentIndex += 1
        let (record, bytes) = try motion.segment(
            id: "\(stream.id)/seg:\(metadataSegmentIndex)",
            endingAtNs: due,
            coverage: &account)
        // ⚠ The bytes are handed over as a provider like every other payload,
        // so `ENC` 7c's manifest-before-payload ordering holds for the metadata
        // Stream too. `nil` where nothing was sampled, which is the `absent`
        // segment path and correctly carries no payload.
        let provider: CaptureSessionRecorder.ClipProvider? = bytes.map { data in
            { @Sendable in data }
        }
        try recorder.announceSegment(record, coverage: account, clip: provider)
        return record
    }

    /// The `continuous` `metadata` Stream, if the device declared an IMU.
    public var metadataStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.metadata }
    }

    /// `CORE` 7.3c — in response to `arm` where one was sent, and in any case
    /// whenever `settled` changes.
    public func report(_ readiness: ReadinessMeasurement, streamIds: [String] = []) throws {
        try recorder.report(readiness, streamIds: streamIds)
    }

    /// `CORE` 7.3d.
    public func record(_ interruption: InterruptionRecord) throws {
        try recorder.record(interruption)
    }

    /// One shot-anchored Capture and the bytes behind it.
    public func announce(_ assembly: CaptureAssembly, clip: Data?) throws {
        // ⚠ The clip is written to its own file under `clips/` and read back when
        // the payload frames go out after the manifest (`ENC` 7c). Holding a
        // session's clips in memory to satisfy a frame-ordering rule would be
        // hundreds of megabytes for nothing.
        guard let clip else {
            try recorder.announce(assembly)
            return
        }
        let url = bundle.clipsDirectory.appendingPathComponent("\(assembly.record.id).mp4")
        try FileManager.default.createDirectory(at: bundle.clipsDirectory,
                                                withIntermediateDirectories: true)
        try clip.write(to: url, options: .atomic)
        try recorder.announce(assembly, clip: { try Data(contentsOf: url) })
    }

    /// The next segment of a `continuous` Stream.
    public func announceSegment(_ record: PpcpCaptureRecord,
                                coverage: StreamCoverage) throws {
        try recorder.announceSegment(record, coverage: coverage)
    }

    public func coverage(of streamId: String) -> StreamCoverage? {
        recorder.coverage(of: streamId)
    }

    public func countShot() { recorder.countShot() }

    /// `MSG` §9.2 then `ENC` §6, then the finish that emits no bytes (7e).
    ///
    /// - Parameter completeness: ⛔ **asserted**, never inferred (I10). A session
    ///   the application abandoned says `partial` and means it, and a `complete`
    ///   one is refused outright where a `continuous` Stream has unaccounted time
    ///   (I36, CT-I36 (d)).
    public func close(completeness: PpcpCaptureRecord.Completeness = .partial,
                      closedAtNs: Int64? = nil) throws {
        guard isClosed == false else { return }
        isClosed = true
        try recorder.close(completeness: completeness, closedAtNs: closedAtNs)
        try handle.close()
    }
}
