//  RecordingSession.swift
//  The composition D3 left open: a `DevicePeer`, a `SessionBundleWriter` and a
//  `CaptureSessionRecorder`, wired to a file and to the real capture stack.
//
//  ⚠ **Nothing in `Sources/` composed these until D4.** D2 built the declaration
//  and D3 built the bundle, and both were exercised only from their own test
//  suites — which is a working library and not a working application. This is the
//  first place the two meet a real device and a real file.
//
//  ⛔ **Two control regimes, one recording.** `Control.hostless` is `CORE` 4.1b /
//  7.3b: the peer opens its own Session with **no arbitration parameters**,
//  records no `arm` and no `disarm`, and records `readiness` because 7.3c confers
//  that through **Capture** rather than through Live. `Control.hosted` is a
//  Session PinPointStudio opened at `declare`, whose parameters arrive on the
//  wire and whose Shots the host issues.
//
//  ⛔ **What the regime changes is the Mint engine's peer, and that is the whole
//  of it.** `ppcp_mint_pump` reads `timebase_ref`, the session id and the
//  relation set off the peer it was built with, so a mint on the bundle peer
//  while a host is arbitrating would ignore `issue_hold_ns`, stamp `t0` in this
//  device's own clock, and never see the host's Shots. Hosted therefore mints on
//  the **link** peer; hostless mints on the record peer.
//
//  ⛔ **What it does NOT change is the bundle's `session_open`, and not by
//  choice.** `ppcp_peer_session_open` refuses arbitration parameters from a peer
//  that is not `role: host` (5.10e, 7.3a, made structural), and `ENC` 7a/7b make
//  a bundle the owner's outbound frames. So even a hosted recording writes a
//  hostless `session_open` — carrying the host's `Session.id` and `timebase_ref`,
//  which is what every Stream, Capture and Shot in the file must agree with. The
//  consequence is pinned by a test and raised with the protocol team: a bundle
//  from a Session a host arbitrated is indistinguishable from one where no host
//  was present.
//
//  ⚠ **Bytes go through a file handle and nowhere else.** `CaptureCore` opens no
//  file (ground rule 8); the writer hands back every byte in order and this is
//  the embedding that appends them.
//
//  Spec: `CORE` §5.2.1, §7.3, §9; `ENC` §7; `CONF` CT-S4 (1).

import Foundation
import CaptureCore

// MARK: - Peer identity

/// `CORE` 5.2.1a — "generated by the peer and persisted in its own store".
///
/// ⛔ 5.2.1b: **never** a platform device identifier and never an advertising
/// identifier. A random UUID generated once and kept is the whole requirement;
/// `identifierForVendor` would be shorter to write and is exactly what the clause
/// forbids, because it is stable across applications and outside this peer's
/// control.
public enum PeerIdentity {

    private static let key = "org.pinpointstudio.capture.ppcp.peerId"

    /// This peer's id, minted on first use and stable thereafter.
    public static var current: String {
        let defaults = UserDefaults.standard
        if let existing = defaults.string(forKey: key), existing.isEmpty == false {
            return existing
        }
        let minted = "peer:\(UUID().uuidString.lowercased())"
        defaults.set(minted, forKey: key)
        return minted
    }
}

// MARK: - The session

/// One recording session, written to a bundle as it happens.
@MainActor
public final class RecordingSession {

    /// Who controls this Session, decided when it opens and fixed for its life.
    ///
    /// ⛔ **Fixed, because `Session.timebase_ref` is immutable (I16)** and the
    /// bundle's `session_open` is already written by the time a host could turn
    /// up. A host appearing mid-session does not convert one — the next arm opens
    /// a hosted Session, and the hostless one it replaces is what
    /// `SessionOfferService` exists to hand over.
    public enum Control {
        case hostless
        case hosted(HostedSessionContext)

        var hosted: HostedSessionContext? {
            if case .hosted(let context) = self { context } else { nil }
        }
    }

    /// ⚠ Kept so `disarm` and the transfer drain know which regime they are in
    /// without re-deriving it.
    public let control: Control

    public let bundle: SessionBundle
    public let sessionId: String
    public let peerId: String

    private let handle: FileHandle
    private let recorder: CaptureSessionRecorder
    /// Where a Capture goes: the bundle alone, or the bundle and the wire.
    ///
    /// ⚠ Stored because a host's `capture_request` announces through it too, and
    /// a Capture a host asked for must reach the file on exactly the terms one
    /// this device minted does.
    private var detectionSink: (any DetectionSink)?
    /// ⚠ Held only so a host's `capture_request` can reach the ring. Everything
    /// else in this file reaches the device through a closure captured at
    /// construction, which is the shape that keeps the extraction the capture
    /// stack's answer rather than this file's.
    private let device: any CaptureDevice
    private var isClosed = false

    /// D5's pipeline, composed here rather than in a test for the first time.
    /// ⛔ `nil` only where the device declared no microphone — a Session with no
    /// nominator is a legitimate record and not a failure.
    public private(set) var detect: DetectAndMint?
    /// The declaration this Session was opened with, kept because
    /// `CandidateFactory` and the Streams both name things inside it.
    public let declaration: PpcpDeclaration
    /// 8.1d — what every Candidate's raw instant is corrected by.
    public let micToBall: MicToBallDistance

    /// A4's audio retention setting, as the policy the detector enforces.
    ///
    /// ⛔ **It was inert.** `AppModel.audioRetention` has existed since the first
    /// build and never reached `DetectAndMint.Configuration.retention`, so the
    /// user-visible control on the permissions screen changed a label and nothing
    /// else — the exact shape of dishonesty REQ-PRIV-2 forbids, since the setting
    /// is what the privacy label describes.
    public let retention: CandidateAudioRetention

    /// The one wall-clock↔monotonic correspondence this Session carries.
    ///
    /// ⚠ Built from the **same** two readings the `PpcpSessionRecord` epoch
    /// already carries (I15), rather than taken again — two anchors a few
    /// microseconds apart would let a shot be labelled differently depending on
    /// which one a caller reached for.
    public private(set) var anchor: WallClockAnchor = WallClockAnchor(hostTimeNs: 0,
                                                                     wallClock: .distantPast)

    /// - Parameters:
    ///   - device: asked for its declaration. ⛔ Through the port, so the
    ///     declaration comes from the capability the hardware actually enumerated
    ///     (REQ-FPS-1) and never from a spec sheet.
    ///   - mode: which camera and which declared `CaptureProfile` the video
    ///     Stream activates. ⛔ **The mode, not a profile id string** (#102):
    ///     the id a caller would have spelled and the id the declaration emits
    ///     were different, so the Stream named a profile that did not exist
    ///     (5.11a, I5). `nil` takes the first profile the first camera Source
    ///     offers, which is only right when the device has one camera.
    ///   - micToBall: 8.1d — the microphone-to-ball distance and its dispersion.
    ///     ⛔ It reaches every Candidate through `CandidateFactory`; before S4
    ///     nothing supplied one and every device Candidate went out with no
    ///     `tof_correction` at all.
    ///   - control: `.hostless` is the shipping path with no host. `.hosted`
    ///     carries the live link, and moves the Mint engine onto its peer — see
    ///     this file's header for why that is the whole of the difference.
    ///   - declaration: injected when hosted, because `HostLinkSession` already
    ///     built one from this device and sent it. ⛔ Building a second here
    ///     would let the bundle record a declaration the host was never given.
    public init(store: SessionStore,
                device: any CaptureDevice,
                sessionId: String,
                control: Control = .hostless,
                peerId: String = PeerIdentity.current,
                mode: VideoMode? = nil,
                declaration injected: PpcpDeclaration? = nil,
                micToBall: MicToBallDistance = MicToBallDistanceStore.load(),
                retention: CandidateAudioRetention = CandidateAudioRetention()) throws {
        self.control = control
        self.micToBall = micToBall
        self.retention = retention
        self.sessionId = sessionId
        self.peerId = peerId
        self.bundle = try store.makeBundle(sessionId: sessionId, mintingPeerId: peerId)

        let file = bundle.bundleFile
        FileManager.default.createFile(atPath: file.path, contents: nil)
        handle = try FileHandle(forWritingTo: file)

        // ⛔ Read adjacently and used twice. `epoch` is a LABEL (I15): the wall
        // reading names the moment, the host-time reading measures from it.
        let epochWall = Date()
        let epochAtNs = MachClock.hostTimeNs

        self.device = device
        let peer = try DevicePeer(peerId: peerId)
        // ⚠ `emit` is called with each run of bytes in order and never with a
        // whole bundle: `ENC` §7 is a stream, and buffering it would make an
        // interrupted session an empty file rather than a `partial` one (7d).
        let writer = try SessionBundleWriter(peer: peer) { [handle] bytes in
            try handle.write(contentsOf: bytes)
        }
        let declaration = try injected ?? PpcpDeclaration(
            device.ppcpDeclarationInput(peerId: peerId, viewpoint: nil))
        self.declaration = declaration

        recorder = try CaptureSessionRecorder(
            writer: writer,
            declaration: declaration,
            // ⛔ `PpcpSessionRecord` has no arbitration parameters to give, and
            // `epoch` is a LABEL (I15) — a wall instant paired with the capture
            // instant it was read beside, never used to compute an interval.
            // ⛔ Hostless in shape either way — see the header. What changes is
            // WHOSE ids it carries: a hosted recording takes the host's
            // `Session.id` and `timebase_ref`, because every Stream, Capture and
            // Shot in this file has to agree with them.
            session: PpcpSessionRecord(
                id: sessionId,
                timebaseRef: control.hosted?.parameters.timebaseRefId
                    ?? PpcpTimebases.captureId,
                // ⛔ 5.10h — the same adjacent reading the epoch takes, because
                // it *is* the moment this Session opened. Read once above and
                // used twice, so the opening instant and the epoch's instant
                // cannot drift apart by however long the lines between them take.
                //
                // ⚠ **Hosted: this is not the host's `opened_at`.**
                // `session_open` carries none (CR-02 plan §10 #3), so a device
                // cannot learn it and must not invent it. What goes here is this
                // device's own reading of the moment it began recording the
                // Session — set once, never revised, and never a later instant.
                openedAtNs: epochAtNs,
                epochWallUtcNs: Int64(epochWall.timeIntervalSince1970 * 1_000_000_000),
                epochAtNs: epochAtNs,
                epochTimebaseId: PpcpTimebases.captureId))
        // REQ-OFF-8 — the label side of the same epoch, and the only route from a
        // monotonic instant to a date this application shows anyone.
        anchor = WallClockAnchor(hostTimeNs: epochAtNs, wallClock: epochWall)

        // ⛔ The Streams are derived from the declaration, not passed in. A
        // Stream's `source_id`, `profile_id` and `timebase_id` must name things
        // the peer actually declared (5.11a, I5), and a caller assembling them by
        // hand is a caller who can name one that does not exist.
        streams = Self.streams(sessionId: sessionId, declaration: declaration,
                               mode: mode,
                               openedAtNs: MachClock.hostTimeNs)
        // ⛔ 5.11j — a preview Capture is never written to a bundle, and the
        // writer refuses one. So the preview Stream is not opened on the record
        // peer at all: it belongs to the link.
        for stream in streams where stream.kind != PpcpStreamKind.preview {
            try recorder.open(stream: stream)
        }

        // ⚠ **The composition D5 wrote and nothing performed.** `DetectAndMint`
        // existed with a full test suite and no caller: the application recorded
        // Streams and a `readiness` and never a Candidate. This is where the
        // detector, the Mint engine, the time-of-flight correction and the ring
        // meet, and it is the whole of D-compose's device half.
        if let audio = streams.first(where: { $0.kind == PpcpStreamKind.audio }),
           let video = streams.first(where: { $0.kind == PpcpStreamKind.video }) ?? streams
               .first(where: { $0.kind == PpcpStreamKind.audio }) {
            let factory = CandidateFactory(
                declaration: declaration,
                sourceId: audio.sourceId,
                // 6.1d — no `format`, therefore no profile and no canonical
                // conversion to apply.
                profileId: nil,
                timeOfFlight: micToBall.timeOfFlight)
            // ⛔ **The Mint engine's peer is the whole of the regime.**
            // `ppcp_mint_pump` reads `timebase_ref`, the session id and the
            // relation set off the peer it was built with — so hosted mints on
            // the link peer, where the host's arbitration parameters and its
            // issued Shots live, and hostless mints on the record peer.
            let mint = try control.hosted?.mint
                ?? DeviceMint(peer: peer, promotion: DetectAndMint.defaultPromotion())
            // ⛔ **Live bytes are bundle bytes.** The composite exists so the
            // same records reach the file and the wire, and so a dead link
            // cannot stop the file being written — the secondary's error is
            // captured, not thrown.
            let sink: any DetectionSink = if let live = control.hosted?.live {
                CompositeDetectionSink(primary: recorder, secondary: live)
            } else {
                recorder
            }
            detectionSink = sink
            detect = DetectAndMint(
                peer: peer, sink: sink, mint: mint, factory: factory,
                configuration: DetectAndMint.Configuration(
                    sessionId: sessionId, peerId: peerId,
                    // 5.13c — in a hostless Session `timebase_ref` is this
                    // device's own capture timebase, so the conversion is the
                    // identity (I4) and **no relation is asserted for it**. With
                    // a host it is the host's, and the identity breaks — which is
                    // the first of the three causes CT-S4 (6) took to find.
                    timebaseRefId: control.hosted?.parameters.timebaseRefId
                        ?? PpcpTimebases.captureId,
                    audioStream: audio, videoStream: video,
                    retention: retention),
                promotion: DetectAndMint.defaultPromotion(),
                // ⛔ Through the port, so the answer is the capture stack's and
                // not this file's. A ring that is not retaining answers
                // `outside_buffer`, which 8.4b makes a result rather than a
                // failure (I10).
                extractAudio: { [device] requested in device.extractClip(requested) },
                // ⛔ **The whole of E1.2 and E1.3 is this line changing.** It
                // used to be three closures: an extraction, a hardcoded
                // `.lockedConstant(0)` exposure, and no payload provider at all
                // — so every Shot this application ever minted announced a
                // Capture with a fabricated exposure and no bytes behind it.
                // The device now answers with what it actually retained:
                // measured exposure (5.8d), the intrinsics the connection
                // delivered (REQ-OPT-7), a thermal timeline over the interval,
                // and a lazy provider for the clip.
                videoClip: { [device, bundle] requested in
                    let half = (requested.upperBound - requested.lowerBound) / 2
                    var clip = device.retainedClip(
                        aroundNs: requested.lowerBound + half,
                        preNs: half, postNs: half)
                    Self.persist(&clip, forT0Ns: requested.lowerBound + half,
                                 in: bundle)
                    return clip
                })
        }
    }

    // MARK: Detect (CORE §5.12, §8.2i–j, §8.3)

    /// One window of microphone audio, all the way to nomination.
    ///
    /// ⛔ **Every onset is emitted** (5.12c, 8.3b, I8), including the ones this
    /// peer does not believe. The promotion decision is the Mint engine's and
    /// happens in `pumpMint`.
    @discardableResult
    /// ⛔ **Hosted runs inside `perform`, and that is not tidiness.** With a host
    /// the Mint engine and the fan-out's live half both sit on the link peer,
    /// which is a C engine with no internal locking; `PeerLinkPump.perform` is
    /// the only door to it. Hostless touches only this session's own peer and
    /// stays on the MainActor, which is the path that ships with no host at all.
    public func observe(_ window: AudioWindow) async throws -> [DetectAndMint.Detection] {
        guard let detect else { return [] }
        // ⛔ **The detector runs HERE, outside the door.** Nine windows in ten
        // produce nothing, and the tenth reaches the ring through
        // `sampleQueue.sync` — neither belongs inside `perform`, which is the
        // link's only serialised entrance and is shared with sync, liveness,
        // flushes and the transfer drain. Doing this inside cost a real device
        // ~24 seconds of queued audio and every clip with it (27 Aug).
        let detections = try detect.detect(window)
        for _ in detections { recorder.countCandidate() }
        guard detections.isEmpty == false else { return [] }

        // Only the three sends need the peer.
        if let hosted = control.hosted {
            try await hosted.pump.perform { _ in try detect.nominate(detections) }
        } else {
            try detect.nominate(detections)
        }
        return detections
    }

    /// 8.2i–j / 8.3a — mint what is due, extract a clip for each Shot.
    ///
    /// - Parameter nowNs: **capture** time, `tb:hosttime`. ⛔ Not reference time.
    ///   The conversion into `Session.timebase_ref` is done here because only
    ///   here is it known whether the two are the same clock: hostless makes
    ///   `timebase_ref` this device's own capture timebase, so the conversion is
    ///   the identity (I4), and with a host it is emphatically not. Passing
    ///   capture time straight in as if it were reference time is cause 1 of the
    ///   three CT-S4 (6) took to find — 5.13c exactly.
    ///
    /// ⚠ **8.2i1 — no substitution.** Where no relation to the host's clock
    /// exists yet, `instant` answers `nil` and nothing is minted. A zero
    /// substituted here would mint every Candidate at the epoch.
    /// A minted Shot, and the instant it happened **in this device's own clock**.
    ///
    /// ⚠ Both are needed above: `shot.t0Ns` is what crosses the wire (5.13c, the
    /// host's `timebase_ref`), and `captureT0Ns` is what indexes the ring, keys
    /// the clip file and labels the row a person reads.
    public struct MintedShot: Sendable {
        public let shot: PpcpShot
        public let captureT0Ns: Int64
        /// ⚠ Non-nil where the ring had nothing for this Shot, and it says why.
        public let clipDiagnostic: String?
    }

    @discardableResult
    public func pumpMint(nowNs: Int64) async throws -> [MintedShot] {
        guard let detect else { return [] }
        let minted: [PpcpShot]
        var captureInstants: [Int64] = []
        var diagnostics: [String] = []
        if let hosted = control.hosted {
            let reference = hosted.parameters.timebaseRefId
            // 1 — decide what is due. Peer, and cheap: usually nothing.
            let (due, captureT0Ns) = try await hosted.pump
                .perform { peer -> ([PpcpShot], [Int64]) in
                    guard let nowRefNs = try peer.instant(nowNs,
                                                          on: PpcpTimebases.captureId,
                                                          expressedIn: reference)
                    else { return ([], []) }
                    let minted = try detect.mintDue(nowRefNs: nowRefNs)
                    // ⛔ **Back into this device's clock, here, while the peer is
                    // in hand.** 5.13c puts `t0` in the host's `timebase_ref`;
                    // the ring indexes in `tb:hosttime`. ⚠ 8.2i1 — a Shot whose
                    // `t0` cannot be converted is dropped rather than extracted
                    // against a substituted number.
                    var local: [Int64] = []
                    var kept: [PpcpShot] = []
                    for shot in minted {
                        // ⛔ **The Candidate's own instant first, and the
                        // conversion only as a fallback.** This device heard the
                        // ball on the clock the ring indexes; round-tripping
                        // through the host's clock applies a rate across the gap
                        // between two boot origins and lands tens of seconds
                        // out — 47 s, measured, while sync reported 0.0 ms.
                        //
                        // ⚠ The fallback covers a Shot the HOST issued for a
                        // Candidate we never nominated (7.3a's case), where
                        // there is no local instant and a conversion is the only
                        // thing available.
                        if let heard = detect.captureInstant(forShot: shot) {
                            kept.append(shot)
                            local.append(heard)
                        } else if let atNs = try peer.instant(
                            shot.t0Ns, on: reference,
                            expressedIn: PpcpTimebases.captureId) {
                            kept.append(shot)
                            local.append(atNs)
                        }
                    }
                    return (kept, local)
                }
            guard due.isEmpty == false else { return [] }

            // 2 — ⛔ **Outside the door.** This reaches the ring through
            // `sampleQueue.sync` and then writes the clip to disk. Holding the
            // link's only entrance for as long as tens of megabytes take is what
            // starved detection and made every `t0` roll out of a ten-second
            // ring before it could be extracted.
            let pending = detect.extract(due, captureT0Ns: captureT0Ns)
            captureInstants = captureT0Ns
            // ⛔ **Say why there is no clip.** On hardware today "timed, not
            // filmed" has meant an interval in the wrong clock, an interval that
            // had rolled out of a ten-second ring, and a ring that was not
            // retaining — and the Capture record says only `absent` for all
            // three. The reason, the window asked for, and how far behind
            // *now* it was, are what separate them.
            // ⛔ **All three clocks, side by side.** The window came back 59 s in
            // the FUTURE on hardware while sync reported 0.0 ms agreement, and
            // those two cannot both be true. Printing the wire value, the
            // converted value and the capture clock together is what says which
            // of them is wrong — and whether the conversion is even doing
            // anything (identity would mean `timebase_ref` is ours already, and
            // the fault is upstream in the Candidate's own instant).
            diagnostics = zip(due, pending).compactMap { shot, entry -> String? in
                guard entry.clip == nil else { return nil }
                let now = MachClock.hostTimeNs
                let converted = entry.requestedNs.lowerBound + 1_500_000_000
                let seconds = { (ns: Int64) in String(format: "%.3f", Double(ns) / 1e9) }
                let stats = device.ringStats
                return """
                    no clip: \(entry.assembly.record.absentReason ?? "no reason") \
                    · t0(wire, \(reference))=\(seconds(shot.t0Ns)) \
                    · t0(capture)=\(seconds(converted)) \
                    · now(capture)=\(seconds(now)) \
                    · ahead by \(String(format: "%.1f", Double(converted - now) / 1e9))s \
                    · ring \(stats.framesAppended) frames, \
                    \(stats.fragmentsWritten - stats.fragmentsEvicted) fragments
                    """
            }

            // 3 — announce. Peer again.
            minted = try await hosted.pump.perform { _ in try detect.commit(pending) }
        } else {
            minted = try detect.pump(nowRefNs: nowNs)
        }
        let localT0 = control.hosted == nil ? minted.map(\.t0Ns) : captureInstants
        var results: [MintedShot] = []
        for (shot, atNs) in zip(minted, localT0) {
            recorder.countShot()
            // E1.2's thumbnail. ⚠ Only reachable here: the clip is written under
            // a `t0` key inside `videoClip`, because `pump` mints the Capture id
            // *after* asking for the clip — so the two are joined up once the
            // Shot comes back carrying it.
            // ⛔ Capture time — this is the key `persist` wrote the file under,
            // because `videoClip` was asked for a capture-time interval.
            adoptClip(forT0Ns: atNs, captureId: shot.captureIds.first)
            results.append(MintedShot(shot: shot, captureT0Ns: atNs,
                                      clipDiagnostic: diagnostics.first))
        }
        return results
    }

    // MARK: The clip on disk (E1.2)

    /// Where t₀ sits inside an extracted clip. ⚠ Mirrors
    /// `DetectAndMint.Configuration`'s default pre-roll, which is what `pump`
    /// asks the ring for.
    nonisolated static let clipPreNs: Int64 = 1_500_000_000

    /// ⛔ **Materialise the clip NOW, and this is not an optimisation choice.**
    ///
    /// `RetainedClip.payload` reads the ring, and the ring is a **ten-second
    /// rolling buffer**. The bundle writes payloads at `close()` (`ENC` 7c holds
    /// them until after the manifest), by which time the fragments behind a shot
    /// from earlier in the session have long been evicted and the provider would
    /// answer nothing. So the bytes are taken while they still exist and written
    /// to `clips/`, and the provider handed onward reads that file.
    ///
    /// ⚠ The laziness that matters is preserved — a session's clips are ~1.4 GB
    /// and none of them is held in memory. What changes is *where* the provider
    /// reads from: a file rather than a buffer that will not be there.
    nonisolated private static func persist(_ clip: inout RetainedClip,
                                            forT0Ns t0Ns: Int64,
                                            in bundle: SessionBundle) {
        guard let payload = clip.payload else { return }
        do {
            let bytes = try payload()
            try FileManager.default.createDirectory(at: bundle.clipsDirectory,
                                                    withIntermediateDirectories: true)
            let url = Self.pendingClipURL(forT0Ns: t0Ns, in: bundle)
            try bytes.write(to: url, options: .atomic)
            clip.payload = { try Data(contentsOf: url) }
        } catch {
            // ⛔ A clip whose bytes could not be kept is a Capture with no
            // payload, not a Capture with a payload nobody can read. Dropping
            // the provider is what makes the announce honest.
            clip.payload = nil
        }
    }

    /// Keyed on `t0` because the Capture id does not exist yet when the clip is
    /// extracted — `DetectAndMint.pump` mints it afterwards.
    nonisolated private static func pendingClipURL(forT0Ns t0Ns: Int64,
                                                   in bundle: SessionBundle) -> URL {
        bundle.clipsDirectory.appendingPathComponent("t0-\(t0Ns).mp4")
    }

    /// Join the `t0`-keyed clip to the Capture that now names it, and render its
    /// thumbnail.
    ///
    /// ⚠ Thumbnail generation is detached: it decodes a frame, and `pumpMint`
    /// runs on the main actor. A picture for a row is never worth a stutter in
    /// the capture UI.
    private func adoptClip(forT0Ns t0Ns: Int64, captureId: String?) {
        guard let captureId else { return }
        let clipURL = Self.pendingClipURL(forT0Ns: t0Ns, in: bundle)
        guard FileManager.default.fileExists(atPath: clipURL.path) else { return }

        let thumbnailURL = bundle.thumbnailFile(captureId: captureId)
        let directory = bundle.thumbnailsDirectory
        // ⚠ Where t₀ falls inside the clip, not where it falls on the capture
        // clock — the generator only knows about the asset's own timeline.
        let offsetNs = Self.clipPreNs
        Task.detached(priority: .utility) {
            guard let jpeg = try? await ClipThumbnail.jpeg(fromClipAt: clipURL,
                                                           atNs: offsetNs) else { return }
            try? FileManager.default.createDirectory(at: directory,
                                                     withIntermediateDirectories: true)
            try? jpeg.write(to: thumbnailURL, options: .atomic)
        }
    }

    /// The Streams a hostless capture session opens, from what was declared.
    ///
    /// ⚠ §5.11's continuity table is normative and is followed rather than
    /// chosen: `video` is always `shot_windowed`, `metadata` always `continuous`.
    nonisolated static func streams(sessionId: String,
                                    declaration: PpcpDeclaration,
                                    mode: VideoMode?,
                                    openedAtNs: Int64) -> [PpcpStreamRecord] {
        var built: [PpcpStreamRecord] = []

        // ⛔ **The camera the MODE is on, not `sources.first`** (#102). 5.6d
        // declares one Source per physical lens, so with a wide and an
        // ultra-wide both declared, `first` opens an ultra-wide capture's Stream
        // on the wide Source — a Capture attributed to the wrong lens, with the
        // wrong calibration, and nothing in the bundle to show for it.
        //
        // ⚠ Both halves fall back only where there is nothing to be precise
        // about: no mode given, or a mode whose Source or profile the
        // declaration does not carry. A profile id that names nothing is exactly
        // what 5.11a / I5 forbid, so the fallback is the Source's own first
        // profile rather than the caller's string.
        let camera = mode.flatMap { m in
            declaration.sources.first { $0.kind == "camera" && $0.id == m.sourceId }
        } ?? declaration.sources.first { $0.kind == "camera" }

        if let camera,
           let profile = mode.map(\.profileId).flatMap({ id in
               camera.profileIds.contains(id) ? id : nil
           }) ?? camera.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:video:\(camera.id)", sessionId: sessionId,
                sourceId: camera.id, kind: PpcpStreamKind.video,
                profileId: profile, timebaseId: camera.timebaseId,
                continuity: .shotWindowed, openedAtNs: openedAtNs))
        }
        // ⛔ **No `preview` Stream is derived here any more.** Preview belongs
        // to the LINK, not to a recording session: 5.11.2 makes setup and
        // framing its main use, which happens before anything is armed, and
        // 5.11k makes a preview Stream alone an independent mode. `LivePreview`
        // owns it, opened when the host asks (#108). Deriving one here as well
        // would put two preview Streams on one Source and pay the 6.7 ms frame
        // path twice for one picture.
        // ⛔ **A separate `audio` Stream, and it was missing.** 5.12.1a puts the
        // window that explains why detection fired on its own Stream, and D5's
        // `DetectAndMint` requires one — but this composition opened only video
        // and metadata, so nothing in the application could nominate. Muxing it
        // into the video clip is the alternative 5.12.1a rules out: it would
        // retain the full video window of room audio per shot for no diagnostic
        // benefit, a privacy cost taken by accident.
        if let microphone = declaration.sources.first(where: { $0.kind == "microphone" }) {
            built.append(PpcpStreamRecord(
                id: "str:audio:\(microphone.id)", sessionId: sessionId,
                sourceId: microphone.id, kind: PpcpStreamKind.audio,
                // ⚠ 6.1d — a microphone declares no `format`, so it has no
                // `CaptureProfile` to activate and the Stream names the Source's
                // own id in its place. `PpcpStreamRecord.profileId` is not
                // optional in the library, and this is the honest filler: a
                // profile id that names nothing would be worse.
                profileId: microphone.profileIds.first ?? microphone.id,
                timebaseId: microphone.timebaseId,
                continuity: .shotWindowed, openedAtNs: openedAtNs))
        }
        if let imu = declaration.sources.first(where: { $0.kind == "imu" }),
           let profile = imu.profileIds.first {
            built.append(PpcpStreamRecord(
                id: "str:metadata:\(imu.id)", sessionId: sessionId,
                sourceId: imu.id, kind: PpcpStreamKind.metadata,
                profileId: profile, timebaseId: imu.timebaseId,
                continuity: .continuous, openedAtNs: openedAtNs))
        }
        return built
    }

    /// The Streams this session opened, in the order they were opened.
    public private(set) var streams: [PpcpStreamRecord] = []

    /// The `video` Stream, for a Capture to land on.
    public var videoStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.video }
    }

    /// D4's attitude and gravity, on the `continuous` `metadata` Stream.
    ///
    /// ⛔ **Written since D4 and never started until E1.3.** REQ-CLIP-1 lists
    /// "device attitude and gravity" and REQ-META-1 requires the Stream; the
    /// source, its encoder and its segment builder were all complete and
    /// nothing had ever called `start()`, so the Stream was opened and then
    /// carried nothing.
    private let motion = MotionMetadataSource(timebaseId: PpcpTimebases.captureId)
    /// Where the metadata Stream's coverage has reached.
    private var metadataSegmentIndex = 0

    /// Begin sampling attitude and gravity. ⚠ Only where the Stream was actually
    /// opened — the declaration decides whether this device has an IMU, and a
    /// source sampling into no Stream is motion nobody can account for.
    public func startMetadata() {
        guard metadataStream != nil else { return }
        motion.start()
    }

    public func stopMetadata() { motion.stop() }

    /// ⚠ Best-effort and deliberately not throwing: this runs from `close`,
    /// which runs from `disarm`, and a link that has already gone is the
    /// ordinary reason it fails. The Streams die with the link in that case.
    private func closeHostedStreams() {
        guard let hosted = control.hosted else { return }
        let records = streams
        let atNs = MachClock.hostTimeNs
        Task { [hosted, records, atNs] in
            try? await hosted.pump.perform { peer in
                for stream in records {
                    try? peer.closeStream(id: stream.id, timebaseId: stream.timebaseId,
                                          atNs: atNs)
                }
            }
        }
    }

    /// Opens this session's own Stream records on the link.
    ///
    /// ⚠ Here rather than at the call site so the wire and the bundle cannot be
    /// given two different derivations of the same Streams.
    public func openHostedStreams() async throws {
        try await control.hosted?.openStreams(streams)
    }

    // MARK: Serving a host's capture_request (MSG §7.3)

    /// `MSG` 7.3a/7.3b — a host asks for an interval around a `t0` this device
    /// may never have nominated, and gets a Capture back either way.
    ///
    /// ⛔ **Three isolation domains in one answer, in this order and no other:**
    /// the conversion needs the link peer (inside `perform`), the extraction
    /// needs the capture stack (the MainActor, and `retainedClip` is a
    /// `sampleQueue.sync` underneath), and the announce needs the peer again.
    ///
    /// ⛔ **An absent Capture is a RESULT, not a failure** (I10, 7.3b). A ring
    /// that no longer holds the interval answers `outside_buffer`; it does not
    /// answer `error`, and 7.3b says so explicitly because the two are easy to
    /// conflate when the code path feels like a failure.
    ///
    /// ⚠ **8.2i1 — where the clocks have no relation, nothing is substituted.**
    /// A `t0` that cannot be converted is answered `outside_buffer` as well: this
    /// device genuinely cannot say what it held at an instant it cannot place,
    /// and inventing an identity would extract the wrong seconds of video and
    /// present them as the right ones.
    public func serveCaptureRequest(shotId: String, t0Ns: Int64, t0TimebaseId: String,
                                    preNs: Int64, postNs: Int64,
                                    replyTo: UInt64) async {
        guard let hosted = control.hosted, let video = videoStream else { return }
        let captureId = "cap:\(UUID().uuidString.lowercased())"

        let localT0: Int64? = try? await hosted.pump.perform { peer in
            try peer.instant(t0Ns, on: t0TimebaseId,
                             expressedIn: PpcpTimebases.captureId)
        }

        guard let localT0 else {
            try? await hosted.pump.perform { peer in
                try peer.captureAbsent(captureId: captureId, shotId: shotId,
                                       streamId: video.id,
                                       reason: PpcpAbsentReason.outsideBuffer,
                                       inReplyTo: replyTo)
            }
            return
        }

        var clip = device.retainedClip(aroundNs: localT0, preNs: preNs, postNs: postNs)
        Self.persist(&clip, forT0Ns: localT0, in: bundle)
        let assembly = CaptureBuilder.shotCapture(
            id: captureId, shotId: shotId, stream: video,
            extraction: clip.extraction, exposure: clip.exposure,
            intrinsics: clip.intrinsics, thermal: clip.thermal)

        if assembly.record.completeness == PpcpCaptureRecord.Completeness.absent {
            try? await hosted.pump.perform { peer in
                try peer.captureAbsent(captureId: captureId, shotId: shotId,
                                       streamId: video.id,
                                       reason: assembly.record.absentReason
                                           ?? PpcpAbsentReason.outsideBuffer,
                                       inReplyTo: replyTo)
            }
            return
        }

        // ⚠ Through the same sink the detector uses, so a Capture a host asked
        // for reaches the bundle on exactly the terms one this device minted
        // does — "live bytes are bundle bytes" is not conditional on who asked.
        // ⚠ Read out on the MainActor, then handed in. `perform`'s closure is
        // `@Sendable` and runs on the pump's executor, so it cannot reach an
        // isolated property — and `DetectionSink` is `AnyObject`-bound and
        // `@unchecked Sendable` by construction, which is what makes passing the
        // reference legitimate rather than a hole.
        guard let sink = detectionSink else { return }
        try? await hosted.pump.perform { [payload = clip.payload] _ in
            try sink.announce(assembly, clip: payload)
        }
    }

    /// What the library says has happened to each announced payload.
    ///
    /// ⚠ **Read from the library's transfer table, never from a count this file
    /// kept.** `payload_ack` and `capture_committed` fill it, and 8.4b forbids an
    /// owner setting `confirmed` on its own authority — so the only honest source
    /// of `In Studio` is the receiver's own statement.
    public var transferRows: [PpcpTransferRow] {
        control.hosted?.live.transferRows ?? []
    }

    // MARK: The bulk drain (E3.4)

    private var transferTask: Task<Void, Never>?

    /// One 32 KiB chunk per `perform`, and that is not a tuning choice.
    ///
    /// ⛔ `libppcp` encodes each originated message into a **64 KiB per-channel**
    /// queue (the cause of #98), and `perform` flushes once at the end — so at
    /// most one chunk of `PayloadTransferQueue.chunkBytes` can clear per pass.
    /// A larger budget would not send more; it would fail `PPCP_ERR_NOSPACE`
    /// against a queue that has not been drained yet.
    nonisolated static let transferBudgetBytes = 32 << 10

    /// Drains queued payload onto the bulk channel for as long as there is any.
    ///
    /// ⚠ **A tight loop rather than a ticker, and off the MainActor.** `CORE` T2
    /// makes the socket's backpressure the thing that decides how fast this
    /// goes: each pass is one actor hop, one chunk, one flush, and the next pass
    /// waits on the one before it. A 100 ms ticker at one chunk a tick would
    /// move 320 KB/s and take well over a minute to shift a single clip.
    ///
    /// ⛔ The 20 ms sleep is only for the **idle** case, so an armed session with
    /// nothing queued is not a spin.
    public func startTransferring() {
        guard let hosted = control.hosted else { return }
        transferTask?.cancel()
        transferTask = Task.detached(priority: .utility) {
            while Task.isCancelled == false {
                let sent = (try? await hosted.pump.perform { _ in
                    try hosted.queue.pump(budgetBytes: Self.transferBudgetBytes)
                }) ?? 0
                if sent == 0 {
                    try? await Task.sleep(for: .milliseconds(20))
                }
            }
        }
    }

    public func stopTransferring() {
        transferTask?.cancel()
        transferTask = nil
    }

    /// The next `metadata` segment, if one is due.
    ///
    /// ⛔ **A `continuous` Stream must account for its whole open interval**
    /// (I36), and `close(completeness: .complete)` already refuses a Session
    /// with an unaccounted tail. So this is called on a ticker rather than when
    /// samples happen to be ready — and `segment` produces an `absent` segment
    /// where nothing was sampled, because 5.11c2 makes a named span carrying
    /// nothing an assertion and silence merely a gap in the record.
    @discardableResult
    public func pumpMetadata(nowNs: Int64) throws -> PpcpCaptureRecord? {
        guard let stream = metadataStream,
              var account = recorder.coverage(of: stream.id) else { return nil }
        let due = account.accountedThroughNs
            + Int64(MotionMetadataSource.segmentSeconds * 1_000_000_000)
        guard nowNs >= due else { return nil }

        metadataSegmentIndex += 1
        let (record, bytes) = try motion.segment(
            id: "\(stream.id)/seg:\(metadataSegmentIndex)",
            endingAtNs: due,
            coverage: &account)
        // ⚠ The bytes are handed over as a provider like every other payload,
        // so `ENC` 7c's manifest-before-payload ordering holds for the metadata
        // Stream too. `nil` where nothing was sampled, which is the `absent`
        // segment path and correctly carries no payload.
        let provider: CaptureSessionRecorder.ClipProvider? = bytes.map { data in
            { @Sendable in data }
        }
        try recorder.announceSegment(record, coverage: account, clip: provider)
        return record
    }

    /// The `continuous` `metadata` Stream, if the device declared an IMU.
    public var metadataStream: PpcpStreamRecord? {
        streams.first { $0.kind == PpcpStreamKind.metadata }
    }

    /// `CORE` 7.3c — in response to `arm` where one was sent, and in any case
    /// whenever `settled` changes.
    public func report(_ readiness: ReadinessMeasurement, streamIds: [String] = []) throws {
        try recorder.report(readiness, streamIds: streamIds)
    }

    /// `CORE` 7.3d.
    public func record(_ interruption: InterruptionRecord) throws {
        try recorder.record(interruption)
    }

    /// One shot-anchored Capture and the bytes behind it.
    public func announce(_ assembly: CaptureAssembly, clip: Data?) throws {
        // ⚠ The clip is written to its own file under `clips/` and read back when
        // the payload frames go out after the manifest (`ENC` 7c). Holding a
        // session's clips in memory to satisfy a frame-ordering rule would be
        // hundreds of megabytes for nothing.
        guard let clip else {
            try recorder.announce(assembly)
            return
        }
        let url = bundle.clipsDirectory.appendingPathComponent("\(assembly.record.id).mp4")
        try FileManager.default.createDirectory(at: bundle.clipsDirectory,
                                                withIntermediateDirectories: true)
        try clip.write(to: url, options: .atomic)
        try recorder.announce(assembly, clip: { try Data(contentsOf: url) })
    }

    /// The next segment of a `continuous` Stream.
    public func announceSegment(_ record: PpcpCaptureRecord,
                                coverage: StreamCoverage) throws {
        try recorder.announceSegment(record, coverage: coverage)
    }

    public func coverage(of streamId: String) -> StreamCoverage? {
        recorder.coverage(of: streamId)
    }

    public func countShot() { recorder.countShot() }

    /// `MSG` §9.2 then `ENC` §6, then the finish that emits no bytes (7e).
    ///
    /// - Parameter completeness: ⛔ **asserted**, never inferred (I10). A session
    ///   the application abandoned says `partial` and means it, and a `complete`
    ///   one is refused outright where a `continuous` Stream has unaccounted time
    ///   (I36, CT-I36 (d)).
    public func close(completeness: PpcpCaptureRecord.Completeness = .partial,
                      closedAtNs: Int64? = nil) throws {
        guard isClosed == false else { return }
        isClosed = true
        // ⚠ Whatever is still queued stops here. 5.14g's exits are the library's
        // to decide, and an unsent payload is not lost — it is in the bundle,
        // which is the whole of "live bytes are bundle bytes".
        stopTransferring()
        // ⛔ **Close this session's Streams on the LINK peer, which outlives it.**
        // 5.1a fixes a Stream's identity for its lifetime and `peer_stream_add`
        // refuses an id the peer already holds — so without this, the second arm
        // on one link re-opens the ids the first left behind and is refused.
        // 5.1d makes an owner-initiated close legal, and PinPointStudio began
        // handling `stream_close` on 27 Aug (their own missing-call-site list).
        closeHostedStreams()
        try recorder.close(completeness: completeness, closedAtNs: closedAtNs)
        try handle.close()
    }
}
